In [ ]:
# ============================================================
# MONAI DICOM Reader Benchmark
#
# Compare:
#   1. PyDICOM
#   2. SimpleITK
#   3. MONAI PydicomReader
#
# Metrics:
#   • Read success
#   • Metadata consistency
#   • Pixel consistency
#   • Shape
#   • Dtype
#   • Multi-frame support
#   • Performance
#
# Author:
# ============================================================

In [ ]:
import os
import time
import traceback
from pathlib import Path

import numpy as np
import pandas as pd

import pydicom
import SimpleITK as sitk

from monai.data import PydicomReader

In [ ]:
# ============================================================
# ROOTS
# ============================================================
BASE_DIR = Path(".").resolve()

DATASET = BASE_DIR / "Datasets"

WORKSPACE_DIR = BASE_DIR.parent

# ------------------------------------------------------------
# INPUT DATASET FOLDERS
# ------------------------------------------------------------

DATASET_ROOTS = [
    DATASET / "Aliza",
    DATASET / "AIIMS",
    DATASET / "Breast_Lesions_USG",
    DATASET / "MONAI",
    DATASET / "ReMIND",
    DATASET / "Heartcycle",
    DATASET / "UTA4",
    DATASET / "UTA7",
    DATASET / "UTA10",
    DATASET / "TCIA_IDC_Prostate_MRI_US_Biopsy",
    
]
# ============================================================
# OUTPUT
# ============================================================

OUTPUT_DIR = Path("benchmark_results")
OUTPUT_DIR.mkdir(exist_ok=True)

CSV_PATH = OUTPUT_DIR / "benchmark.csv"

In [ ]:
# ============================================================
# DICOM VALIDATION
# ============================================================

def is_dicom_file(path):

    try:

        with open(path, "rb") as f:

            f.seek(128)

            if f.read(4) == b"DICM":
                return True

        ds = pydicom.dcmread(
            path,
            stop_before_pixels=True,
            force=False
        )

        return any([
            hasattr(ds, "PatientID"),
            hasattr(ds, "StudyInstanceUID"),
            hasattr(ds, "SeriesInstanceUID"),
            hasattr(ds, "SOPInstanceUID")
        ])

    except Exception:

        return False

# ============================================================
# DISCOVERY
# ============================================================

def collect_dicom_files(roots):

    files = []

    print("="*70)
    print("Collecting DICOM files")
    print("="*70)

    for root in roots:

        if not root.exists():

            continue

        print(root)

        for f in root.rglob("*"):

            if not f.is_file():
                continue

            if f.suffix.lower() in [".dcm",".dicom"]:

                if is_dicom_file(f):

                    files.append(f)

            elif f.suffix == "":

                if is_dicom_file(f):

                    files.append(f)

    files = sorted(files)

    print()

    print("Total DICOM:",len(files))

    return files

# ============================================================
# BASIC METADATA
# ============================================================

def metadata_from_dataset(ds):

    meta = {}

    tags = [

        "PatientID",

        "Modality",

        "Manufacturer",

        "ManufacturerModelName",

        "Rows",

        "Columns",

        "BitsAllocated",

        "BitsStored",

        "SamplesPerPixel",

        "PhotometricInterpretation",

        "PixelRepresentation",

        "TransferSyntaxUID",

        "NumberOfFrames"

    ]

    for tag in tags:

        try:

            meta[tag] = str(ds.get(tag,""))

        except:

            meta[tag] = ""

    return meta

# ============================================================
# PIXEL STATISTICS
# ============================================================

def pixel_statistics(arr):

    if arr is None:

        return None

    arr = np.asarray(arr)

    stats = {}

    stats["shape"] = arr.shape

    stats["dtype"] = str(arr.dtype)

    stats["min"] = float(arr.min())

    stats["max"] = float(arr.max())

    stats["mean"] = float(arr.mean())

    stats["std"] = float(arr.std())

    return stats

# ============================================================
# ARRAY COMPARISON
# ============================================================

def compare_arrays(a,b):

    result = {}

    if a is None or b is None:

        result["equal"] = False

        result["rmse"] = np.nan

        result["max_error"] = np.nan

        return result

    a = np.asarray(a)

    b = np.asarray(b)

    result["shape_equal"] = a.shape == b.shape

    result["dtype_equal"] = a.dtype == b.dtype

    if a.shape != b.shape:

        result["equal"] = False

        result["rmse"] = np.nan

        result["max_error"] = np.nan

        return result

    result["equal"] = np.array_equal(a,b)

    diff = a.astype(np.float64)-b.astype(np.float64)

    result["rmse"] = np.sqrt(np.mean(diff**2))

    result["max_error"] = np.max(np.abs(diff))

    return result

# ============================================================
# TIMER
# ============================================================

class Timer:

    def __enter__(self):

        self.t0 = time.perf_counter()

        return self

    def __exit__(self,*args):

        self.elapsed = time.perf_counter()-self.t0

In [2]:
# ============================================================
# READER : PYDICOM
# ============================================================

def read_with_pydicom(dcm_path):

    result = {
        "success": False,
        "reader": "PyDICOM",
        "time": np.nan,
        "exception": "",
        "dataset": None,
        "pixels": None,
        "metadata": {},
        "stats": {},
    }

    try:

        with Timer() as t:

            ds = pydicom.dcmread(
                str(dcm_path),
                force=True
            )

            pixels = ds.pixel_array

        result["success"] = True
        result["time"] = t.elapsed
        result["dataset"] = ds
        result["pixels"] = pixels
        result["metadata"] = metadata_from_dataset(ds)
        result["stats"] = pixel_statistics(pixels)

    except Exception as e:

        result["exception"] = traceback.format_exc()

    return result


# ============================================================
# READER : SimpleITK
# ============================================================

def read_with_simpleitk(dcm_path):

    result = {
        "success": False,
        "reader": "SimpleITK",
        "time": np.nan,
        "exception": "",
        "pixels": None,
        "stats": {},
        "spacing": None,
        "origin": None,
        "direction": None,
    }

    try:

        with Timer() as t:

            image = sitk.ReadImage(str(dcm_path))

            pixels = sitk.GetArrayFromImage(image)

        result["success"] = True
        result["time"] = t.elapsed
        result["pixels"] = pixels
        result["stats"] = pixel_statistics(pixels)

        try:
            result["spacing"] = image.GetSpacing()
        except:
            pass

        try:
            result["origin"] = image.GetOrigin()
        except:
            pass

        try:
            result["direction"] = image.GetDirection()
        except:
            pass

    except Exception:

        result["exception"] = traceback.format_exc()

    return result


# ============================================================
# INITIALIZE MONAI READER
# ============================================================

try:

    monai_reader = PydicomReader()

except Exception:

    monai_reader = None


# ============================================================
# READER : MONAI
# ============================================================

def read_with_monai(dcm_path):

    result = {
        "success": False,
        "reader": "MONAI",
        "time": np.nan,
        "exception": "",
        "pixels": None,
        "stats": {},
        "metadata": {},
    }

    if monai_reader is None:

        result["exception"] = "MONAI PydicomReader unavailable"

        return result

    try:

        with Timer() as t:

            img = monai_reader.read(str(dcm_path))

            pixels, meta = monai_reader.get_data(img)

        result["success"] = True
        result["time"] = t.elapsed

        result["pixels"] = np.asarray(pixels)

        result["stats"] = pixel_statistics(result["pixels"])

        if isinstance(meta, dict):

            result["metadata"] = meta

    except Exception:

        result["exception"] = traceback.format_exc()

    return result


# ============================================================
# PRINT READER SUMMARY
# ============================================================

def print_reader_summary(result):

    print("=" * 70)

    print(result["reader"])

    print("=" * 70)

    print("Success :", result["success"])

    print("Time    :", result["time"])

    if result["success"]:

        stats = result["stats"]

        print("Shape   :", stats["shape"])
        print("Dtype   :", stats["dtype"])
        print("Min     :", stats["min"])
        print("Max     :", stats["max"])
        print("Mean    :", stats["mean"])
        print("Std     :", stats["std"])

    else:

        print(result["exception"])


# ============================================================
# QUICK SANITY TEST
# ============================================================

candidate_files = collect_dicom_files(DATASET_ROOTS)

print()

print("Found", len(candidate_files), "DICOM files")

if len(candidate_files):

    test_file = candidate_files[0]

    print("\nTesting readers on:\n")
    print(test_file)

    py = read_with_pydicom(test_file)

    sitk_result = read_with_simpleitk(test_file)

    monai = read_with_monai(test_file)

    print_reader_summary(py)

    print_reader_summary(sitk_result)

    print_reader_summary(monai)

======================================================================
Collecting DICOM files
======================================================================
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\Aliza
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AIIMS
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\Breast_Lesions_USG
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\MONAI
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\ReMIND
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\Heartcycle
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UTA4
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UTA7
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UTA10
C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\TCIA_IDC_Prostate_MRI_US_Biopsy

Total DICOM: 3468

Found 3468 DICOM files

Testing readers on:

C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AIIMS\AIIMSJ_GE_Vivid_E95\Q3EDC380.dcm
======================================================================
PyDICOM
======================================================================
Success : True
Time    : 1.308778499999999
Shape   : (126, 708, 1016, 3)
Dtype   : uint8
Min     : 0.0
Max     : 255.0
Mean    : 92.70084474124704
Std     : 54.46496664853589
======================================================================
SimpleITK
======================================================================
Success : True
Time    : 2.0651714000000005
Shape   : (126, 708, 1016, 3)
Dtype   : uint8
Min     : 0.0
Max     : 255.0
Mean    : 21.32530960407256
Std     : 34.28681016074183
======================================================================
MONAI
======================================================================
Success : True
Time    : 1.4006465000000006
Shape   : (708, 126, 1016, 3)
Dtype   : uint8
Min     : 0.0
Max     : 255.0
Mean    : 92.70084474124704
Std     : 54.46496664853578

In [3]:
# ============================================================
# DICOM METADATA EXTRACTION
# ============================================================

def extract_dicom_information(ds):

    info = {}

    tags = [

        "SOPClassUID",

        "TransferSyntaxUID",

        "PhotometricInterpretation",

        "SamplesPerPixel",

        "BitsAllocated",

        "BitsStored",

        "HighBit",

        "PixelRepresentation",

        "Rows",

        "Columns",

        "PlanarConfiguration",

        "NumberOfFrames",

        "Manufacturer",

        "ManufacturerModelName",

        "Modality",

        "UltrasoundColorDataPresent",

        "LossyImageCompression",

        "LossyImageCompressionMethod"

    ]

    for tag in tags:

        try:

            info[tag] = str(ds.get(tag, ""))

        except:

            info[tag] = ""

    return info

In [4]:
# ============================================================
# PHOTOMETRIC
# ============================================================

def validate_photometric(ds):

    report = {}

    report["Photometric"] = str(
        ds.get(
            "PhotometricInterpretation",
            ""
        )
    )

    report["SamplesPerPixel"] = int(
        ds.get(
            "SamplesPerPixel",
            1
        )
    )

    report["PlanarConfiguration"] = str(
        ds.get(
            "PlanarConfiguration",
            ""
        )
    )

    report["Color"] = \
        report["SamplesPerPixel"] > 1

    return report

In [5]:
# ============================================================
# TRANSFER SYNTAX
# ============================================================

def classify_transfer_syntax(ds):

    uid = str(
        ds.file_meta.TransferSyntaxUID
    )

    if uid == "1.2.840.10008.1.2":

        return "Implicit VR Little"

    if uid == "1.2.840.10008.1.2.1":

        return "Explicit VR Little"

    if uid == "1.2.840.10008.1.2.2":

        return "Explicit VR Big"

    if uid.startswith("1.2.840.10008.1.2.4"):

        return "JPEG"

    if uid.startswith("1.2.840.10008.1.2.5"):

        return "RLE"

    return uid

In [6]:
# ============================================================
# FAILURE CLASSIFICATION
# ============================================================

def classify_failure(py,
                     sitk_result,
                     monai):

    report = {}

    report["Status"] = "PASS"

    report["Reason"] = ""

    if not py["success"]:

        report["Status"] = "FAIL"

        report["Reason"] = "PyDICOM Read Failure"

        return report

    if not sitk_result["success"]:

        report["Status"] = "FAIL"

        report["Reason"] = "SimpleITK Read Failure"

        return report

    if not monai["success"]:

        report["Status"] = "FAIL"

        report["Reason"] = "MONAI Read Failure"

        return report

    p = canonicalize_array(py["pixels"])

    s = canonicalize_array(sitk_result["pixels"])

    m = canonicalize_array(monai["pixels"])

    if p.shape != s.shape:

        report["Status"] = "WARNING"

        report["Reason"] = \
            "PyDICOM vs SimpleITK Shape"

    elif p.shape != m.shape:

        report["Status"] = "WARNING"

        report["Reason"] = \
            "PyDICOM vs MONAI Shape"

    elif not np.array_equal(p,s):

        report["Status"] = "WARNING"

        report["Reason"] = \
            "Pixel Difference PyDICOM/SimpleITK"

    elif not np.array_equal(p,m):

        report["Status"] = "WARNING"

        report["Reason"] = \
            "Pixel Difference PyDICOM/MONAI"

    return report

In [7]:
# ============================================================
# CANONICALIZE ARRAY
#
# Convert every reader output to the same convention
#
# Final convention:
#
#   Grayscale
#       (H,W)
#       (Frames,H,W)
#
#   RGB
#       (H,W,3)
#       (Frames,H,W,3)
# ============================================================

def canonicalize_array(arr):

    if arr is None:
        return None

    arr = np.asarray(arr)

    # -------------------------
    # Already 2D
    # -------------------------

    if arr.ndim == 2:
        return arr

    # -------------------------
    # RGB image
    # -------------------------

    if arr.ndim == 3:

        if arr.shape[-1] in (3,4):
            return arr

        if arr.shape[0] in (3,4):

            # Channel-first
            return np.moveaxis(arr,0,-1)

        return arr

    # -------------------------
    # Multi-frame RGB
    # -------------------------

    if arr.ndim == 4:

        # (F,C,H,W)

        if arr.shape[1] in (3,4):

            arr = np.moveaxis(arr,1,-1)

            return arr

        return arr

    return arr


# ============================================================
# ARRAY REPORT
# ============================================================

def describe_array(arr):

    if arr is None:

        return "None"

    arr=np.asarray(arr)

    return {

        "shape":arr.shape,

        "dtype":str(arr.dtype),

        "min":float(arr.min()),

        "max":float(arr.max()),

        "mean":float(arr.mean()),

        "std":float(arr.std()),

        "ndim":arr.ndim

    }


# ============================================================
# PIXEL DIFFERENCE REPORT
# ============================================================

def pixel_difference_report(a,b):

    report={}

    a=canonicalize_array(a)

    b=canonicalize_array(b)

    if a is None or b is None:

        report["status"]="Missing"

        return report

    report["shapeA"]=a.shape
    report["shapeB"]=b.shape

    report["dtypeA"]=str(a.dtype)
    report["dtypeB"]=str(b.dtype)

    report["shape_equal"]=a.shape==b.shape

    if a.shape!=b.shape:

        report["status"]="Different Shape"

        return report

    diff=a.astype(np.float64)-b.astype(np.float64)

    report["equal"]=np.array_equal(a,b)

    report["allclose"]=np.allclose(a,b)

    report["rmse"]=np.sqrt(np.mean(diff**2))

    report["mae"]=np.mean(np.abs(diff))

    report["max_error"]=np.max(np.abs(diff))

    report["different_pixels"]=np.count_nonzero(diff)

    report["status"]="Compared"

    return report

In [8]:
# ============================================================
# FRAME COUNT
# ============================================================

def frame_count(arr):

    if arr is None:
        return None

    arr = np.asarray(arr)

    if arr.ndim == 2:
        return 1

    if arr.ndim == 3:

        if arr.shape[-1] in (3,4):
            return 1

        return arr.shape[0]

    if arr.ndim == 4:
        return arr.shape[0]

    return None

In [9]:
def throughput(arr,time_taken):

    if arr is None:

        return np.nan

    pixels = np.asarray(arr).size

    return pixels / time_taken

In [10]:
# ============================================================
# METADATA COMPARISON
# ============================================================

def compare_metadata(meta1, meta2):

    result = {}

    keys = sorted(set(meta1.keys()).union(meta2.keys()))

    for k in keys:

        v1 = str(meta1.get(k, ""))

        v2 = str(meta2.get(k, ""))

        result[k + "_equal"] = (v1 == v2)

    return result


# ============================================================
# BUILD ONE RESULT ROW
# ============================================================

def build_result_row(dcm_file,
                     py,
                     sitk_result,
                     monai):

    row = {}

    # --------------------------------------------------------
    # File information
    # --------------------------------------------------------

    row["File"] = str(dcm_file)

    row["Filename"] = dcm_file.name

    row["ReaderCount"] = \
        int(py["success"]) + \
        int(sitk_result["success"]) + \
        int(monai["success"])

    # --------------------------------------------------------
    # Success
    # --------------------------------------------------------

    row["PyDICOM_OK"] = py["success"]

    row["SimpleITK_OK"] = sitk_result["success"]

    row["MONAI_OK"] = monai["success"]

    # --------------------------------------------------------
    # Read Time
    # --------------------------------------------------------

    row["Py_Time"] = py["time"]

    row["SimpleITK_Time"] = sitk_result["time"]

    row["MONAI_Time"] = monai["time"]

    # --------------------------------------------------------
    # Throughput
    # --------------------------------------------------------
    
    row["Py_Throughput"] = throughput(
        py["pixels"],
        py["time"]
    )
    
    row["SimpleITK_Throughput"] = throughput(
        sitk_result["pixels"],
        sitk_result["time"]
    )
    
    row["MONAI_Throughput"] = throughput(
        monai["pixels"],
        monai["time"]
    )

    # --------------------------------------------------------
    # Shape
    # --------------------------------------------------------

    if py["success"]:
        row["Py_Shape"] = str(py["stats"]["shape"])
        row["Py_Dtype"] = py["stats"]["dtype"]
    else:
        row["Py_Shape"] = ""
        row["Py_Dtype"] = ""

    if sitk_result["success"]:
        row["SimpleITK_Shape"] = str(
            sitk_result["stats"]["shape"]
        )
        row["SimpleITK_Dtype"] = \
            sitk_result["stats"]["dtype"]
    else:
        row["SimpleITK_Shape"] = ""
        row["SimpleITK_Dtype"] = ""

    if monai["success"]:
        row["MONAI_Shape"] = \
            str(monai["stats"]["shape"])
        row["MONAI_Dtype"] = \
            monai["stats"]["dtype"]
    else:
        row["MONAI_Shape"] = ""
        row["MONAI_Dtype"] = ""

    # --------------------------------------------------------
    # Pixel comparisons
    # --------------------------------------------------------

    ps = compare_arrays(
        py["pixels"],
        sitk_result["pixels"]
    )

    pm = compare_arrays(
        py["pixels"],
        monai["pixels"]
    )

    sm = compare_arrays(
        sitk_result["pixels"],
        monai["pixels"]
    )

    # ------------------------

    row["Py_vs_SimpleITK_Equal"] = \
        ps["equal"]

    row["Py_vs_SimpleITK_RMSE"] = \
        ps["rmse"]

    row["Py_vs_SimpleITK_MaxError"] = \
        ps["max_error"]

    # ------------------------

    row["Py_vs_MONAI_Equal"] = \
        pm["equal"]

    row["Py_vs_MONAI_RMSE"] = \
        pm["rmse"]

    row["Py_vs_MONAI_MaxError"] = \
        pm["max_error"]

    # ------------------------

    row["SimpleITK_vs_MONAI_Equal"] = \
        sm["equal"]

    row["SimpleITK_vs_MONAI_RMSE"] = \
        sm["rmse"]

    row["SimpleITK_vs_MONAI_MaxError"] = \
        sm["max_error"]

    # --------------------------------------------------------
    # Metadata
    # --------------------------------------------------------

    if py["success"]:

        row.update(py["metadata"])

    return row


# ============================================================
# BENCHMARK
# ============================================================

results = []

print()

print("="*70)
print("Running Benchmark")
print("="*70)

total = len(candidate_files)

for idx, dcm_file in enumerate(candidate_files):

    print()

    print(f"[{idx+1}/{total}] {dcm_file.name}")

    py = read_with_pydicom(dcm_file)

    sitk_result = read_with_simpleitk(dcm_file)
    
    monai = read_with_monai(dcm_file)
    
    # -------------------------
    # DICOM metadata
    # -------------------------
    
    ds = py["dataset"]
    
    dicom_info = extract_dicom_information(ds)
    
    photo_info = validate_photometric(ds)
    
    syntax = classify_transfer_syntax(ds)
    
    failure = classify_failure(
        py,
        sitk_result,
        monai
    )
    
    # -------------------------
    # Build result row
    # -------------------------
    
    row = build_result_row(
        dcm_file,
        py,
        sitk_result,
        monai
    )
    
    row.update(dicom_info)
    
    row.update(photo_info)
    
    row["TransferSyntax"] = syntax
    
    row["ValidationStatus"] = failure["Status"]
    
    row["FailureReason"] = failure["Reason"]
    
    row["Frames_PyDICOM"] = frame_count(py["pixels"])
    
    row["Frames_SimpleITK"] = frame_count(
        sitk_result["pixels"]
    )
    
    row["Frames_MONAI"] = frame_count(
        monai["pixels"]
    )
    
    results.append(row)

print()

print("="*70)
print("Benchmark Finished")
print("="*70)

======================================================================
Running Benchmark
======================================================================

[1/3468] Q3EDC380.dcm

[2/3468] Q3EDCA02.dcm

[3/3468] Q3EDCBG4.dcm

[4/3468] Q3EDCH86.dcm

[5/3468] Q3EDCK08.dcm

[6/3468] IM_0001.dcm

[7/3468] IM_0002.dcm

[8/3468] usvolume_4D.dcm

[9/3468] US-GE-4AICL142.dcm

[10/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084400.0.dcm

[11/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084428.0.dcm

[12/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084457.0.dcm

[13/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084523.0.dcm

[14/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084559.0.dcm

[15/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084627.0.dcm

[16/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084654.0.dcm

[17/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084725.0.dcm

[18/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084753.0.dcm

[19/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084825.0.dcm

[20/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084853.0.dcm

[21/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826084940.0.dcm

[22/3468] US.1.3.46.670589.14.3000.100.2.199999.20110826085516.0.dcm

[23/3468] us_kretz.dcm

[24/3468] us_kretz2.dcm

[25/3468] us_valid_pixel_aspect.dcm

[26/3468] 055829-00000000.dcm

[27/3468] us_acuson.dcm

[28/3468] us_acuson2.dcm

[29/3468] us_rle_ybr.dcm

The decoded RLE segment contains non-conformant padding - 276025 vs. 276024 bytes expected

[30/3468] 8c780494-786d-4ed7-b2a0-24fe18bd8dce.dcm

[31/3468] bf1b0a44-60ca-4d20-a6e2-dde3ae34ea53.dcm

[32/3468] 91d91920-3d47-4a81-8a45-3fa9fdb2b70a.dcm

[33/3468] 99d9bce9-a4d5-4c53-bdb3-65cbd64b0d80.dcm

[34/3468] 0d3220cf-c1e2-45dd-b3e2-af125beb8a15.dcm

[35/3468] 39ea0987-7be5-4b9c-aa5c-a538ab0f085a.dcm

[36/3468] 495f767d-377c-41ed-8df7-c79c44b23d02.dcm

[37/3468] 4a2c814f-ecaa-4f8e-9560-d12d73136891.dcm

[38/3468] 84a0a112-63c6-4aff-85e3-b36715c38f03.dcm

[39/3468] ab591baa-8f19-46e2-87ed-8f65adbcdd28.dcm

[40/3468] 9c0b66c1-7cfc-4532-8465-2653574096bd.dcm

[41/3468] 574a4303-0c53-4982-b2b2-19f0670c94ff.dcm

[42/3468] a8f6217f-e04d-4b2a-92ba-dd13274260af.dcm

[43/3468] cc79a9d0-2a38-4de6-b3b5-a15c97e81143.dcm

[44/3468] 08453398-3c91-4159-adf9-77bd4617c61f.dcm

[45/3468] b6643095-f59a-4981-b8c2-b4b5f6f75977.dcm

[46/3468] 645085d6-7b68-4c47-b8f3-e3cc43506581.dcm

[47/3468] 768d05c1-d6a0-43b9-9902-60ceabd25411.dcm

[48/3468] 4a6fad44-7808-4948-9c61-790a372e0904.dcm

[49/3468] b792dd7d-037d-4aff-a4c6-bd1a4da91bf1.dcm

[50/3468] c9e6239f-905b-4dc5-9940-9856ff3e87a8.dcm

[51/3468] d073c4a4-e371-4fe1-9c3c-ea1ca1457e75.dcm

[52/3468] e918c59f-45bf-4672-b5aa-a6de3b2e00fb.dcm

[53/3468] 4ccdad1a-2bb3-47ad-8f02-3cc1bb569930.dcm

[54/3468] f7b1da0e-6038-4e72-88f7-5e1cce8d3420.dcm

[55/3468] 7c84b34c-5bb1-4749-bfed-c33d67050a49.dcm

[56/3468] d7295975-6181-40d4-ac57-7bb513fd52f5.dcm

[57/3468] 9ae77092-3320-4891-94b6-cb9d6261d124.dcm

[58/3468] 0e7e8c4d-53fb-466a-ada5-ca5f5b459dff.dcm

[59/3468] 24fdbe25-ca89-411c-80ed-e1bb034603e6.dcm

[60/3468] e4339c41-2acd-48ed-bfdc-ee9d5de5bce7.dcm

[61/3468] 6facb5b9-e623-4dd9-bf40-f4515f0c4ce3.dcm

[62/3468] 5f04f3b7-e01b-42bf-a825-cde26ada7839.dcm

[63/3468] 6aba3474-6bbe-47f2-b7ca-0de936ce37ce.dcm

[64/3468] 6c226d02-fce7-40c1-8054-2553d63df6e5.dcm

[65/3468] fc515c55-810b-4e43-bd99-2be2026186b6.dcm

[66/3468] 6693706e-585c-4948-80b4-53b62665a753.dcm

[67/3468] 0c45b36e-363b-4433-a65a-ec09536d7e36.dcm

[68/3468] 2a5d491f-03c2-45c8-9e96-21d05956c526.dcm

[69/3468] 22f91db4-5658-4181-bb0f-4d1548a307b1.dcm

[70/3468] e97faaf4-27bd-48e7-9a63-d5a8ed8124b3.dcm

[71/3468] b6b2cf2a-3851-4d57-9c4b-ec1650bf427c.dcm

[72/3468] 8d466ed2-af7f-4992-8e5c-567bc035806d.dcm

[73/3468] 5fef8e59-31ee-443a-ba5e-7fa36f345576.dcm

[74/3468] 786372a8-6bfa-4226-97d6-d29d434d73b0.dcm

[75/3468] 7f803702-e584-4663-84f0-8e46d91284bf.dcm

[76/3468] b22c3f3b-6ba0-4375-9847-5115891724a3.dcm

[77/3468] 7b4d2de1-efc2-4456-a753-0b4d323fd32f.dcm

[78/3468] 80cae88f-c812-45c7-9f6a-51e1f357b481.dcm

[79/3468] c4945b64-34e8-4ce6-a703-17ef7dc3a4fa.dcm

[80/3468] 5c5c4b8d-9821-477d-bfdf-830279e02aca.dcm

[81/3468] dd0957f7-8ee4-418f-98e2-024c8f20338b.dcm

[82/3468] 1b937529-a999-415e-84de-c254119d9c03.dcm

[83/3468] db1917b2-0f7c-4ad7-9b9b-9c94ac700d2a.dcm

[84/3468] 161ed4ff-a6cc-4fd3-b97e-7c811cb6eaea.dcm

[85/3468] 040a9825-9e84-483c-8401-a7407dc75834.dcm

[86/3468] 64cfdc53-1231-4875-88be-c8372af505d0.dcm

[87/3468] 31087c97-dcb3-4af0-9412-9d43eb0c47ef.dcm

[88/3468] e30c07d7-8306-4a1d-8374-76b813767b70.dcm

[89/3468] aacf6142-ae42-4924-a4f6-8145960e5cfc.dcm

[90/3468] d596e218-2786-4b85-a07d-eba6c0f04c4c.dcm

[91/3468] 9faa0694-9c5b-4f2d-bce4-61c357f847bf.dcm

[92/3468] f84e9d0b-863f-4cc3-8899-cd7ef30508e5.dcm

[93/3468] da7d65f9-bec3-47fe-a1fa-a21d2b908ec8.dcm

[94/3468] 736296aa-efb7-40f3-9c02-d72742b9df79.dcm

[95/3468] 3a6ba9e2-c33d-4cf8-865d-781d044d1657.dcm

[96/3468] 64f0965d-0d71-4d0f-ada9-86182b789563.dcm

[97/3468] 0479e010-a1e5-4d47-b89c-909c1e42f9ed.dcm

[98/3468] 83ae22fb-e9d6-471b-a806-57389549fc71.dcm

[99/3468] e0ad2747-cd72-4aa7-86e5-b1fe0a141096.dcm

[100/3468] 005cdf4b-6e80-4f0c-8b60-65d6383118e4.dcm

[101/3468] 58d5153a-b653-4d6e-8baa-7812b30b6be4.dcm

[102/3468] 704ac642-3c6f-48d0-8db4-f9e68c854adc.dcm

[103/3468] 793eb56d-19f8-4dec-a23e-dc0249ab368e.dcm

[104/3468] 477b6569-cff2-4cfd-b2f9-49fec1a0f9a8.dcm

[105/3468] fd3d23ec-0125-4392-9e28-30df7bc8b98a.dcm

[106/3468] a5c25ecd-180b-4e6a-a0e8-2a6cb95df7fe.dcm

[107/3468] 3d4c9600-3614-4486-9c5d-e0cb044f78b0.dcm

[108/3468] 2db84697-f2ae-4e5f-9492-310c98b7107b.dcm

[109/3468] 04e82628-1ae4-47b8-b7e4-69858a9cbe02.dcm

[110/3468] 9fc4da8e-17e6-49c0-8e1f-af67e0d50981.dcm

[111/3468] e4c03535-73fe-45b9-af78-3c9cf2da504b.dcm

[112/3468] 04f6e8fe-75e9-4c4d-baba-0a36495bad25.dcm

[113/3468] 22ef6a0f-3eaf-4c1e-8a37-6458efe1d986.dcm

[114/3468] 25ab5a41-2d87-4db9-9858-4a72d3410690.dcm

[115/3468] a151a00f-8d3e-421e-b11d-04dc8dd0d3ec.dcm

[116/3468] 639b3244-0ab6-4da7-a8f0-efba946ab544.dcm

[117/3468] db3cf47a-a6ea-4ccd-a0c2-905cb3f6ba81.dcm

[118/3468] e4bd92d0-a6a8-467c-810c-37e50e897cd9.dcm

[119/3468] c14d9998-5609-41f1-88c0-e0e40fa3e4cc.dcm

[120/3468] df5b6a0c-3af9-431f-bb85-1c64bb4bd8a9.dcm

[121/3468] 05353349-7267-43d0-8b93-8966db99f954.dcm

[122/3468] 3e50e07d-682a-428d-9ddf-bf347e7f0789.dcm

[123/3468] 8fd1a486-a491-4c25-a86a-ee42916b1ce0.dcm

[124/3468] ea6f4cb3-0ee0-414e-8e24-2bc18eb727c2.dcm

[125/3468] 8c6ce9e9-b1e1-4e0f-99dd-9cda106d02fd.dcm

[126/3468] e33e5b04-c5c7-4e17-a489-6f57ab42000f.dcm

[127/3468] d12cbe2c-c7ed-4b7d-bcac-0e361416ec1d.dcm

[128/3468] 6fe19e3b-8aca-4453-bd26-2be8133b0755.dcm

[129/3468] b8276097-f85b-4a94-ac8a-b071a22bed23.dcm

[130/3468] f38a033b-c127-467d-9f98-5eff350e6f2c.dcm

[131/3468] 7d556b5e-33ba-443c-9acb-e17b6098982d.dcm

[132/3468] 71c7ae85-9395-45ee-b6e5-b39c8ca20ba1.dcm

[133/3468] b4db197a-956b-4e08-9f2e-5ef57fb2d776.dcm

[134/3468] e1a9014a-3870-4bbb-95fc-cc3f9decb98c.dcm

[135/3468] aaf45294-0937-418d-a700-2e33ef4236ac.dcm

[136/3468] bddd70fd-7e82-4fe4-b4b5-c64ad271c9a5.dcm

[137/3468] abf99ded-18ab-4632-8590-fd3f0795e195.dcm

[138/3468] 0073ae19-c128-4f3a-b14c-45e755a76480.dcm

[139/3468] a9cc9b39-72f1-4bb5-89a6-a2107b549682.dcm

[140/3468] 2f569686-cae1-42c5-963f-15f1a490a51a.dcm

[141/3468] 07251227-6871-4ef4-87c9-7efbe2c80c25.dcm

[142/3468] cbb79d7f-c18f-436f-bf58-810327c7b886.dcm

[143/3468] cbb263a3-81d9-45de-97da-061fa80a6cf2.dcm

[144/3468] c9646373-39ba-4817-83c9-c717d29e203b.dcm

[145/3468] b53fca21-0257-499a-815d-66d7065f079d.dcm

[146/3468] 087f5072-a6a4-4b90-8d56-d33c4084f2b0.dcm

[147/3468] 016ec0c0-bc48-4a7f-a248-54030bcf3fad.dcm

[148/3468] efa71aef-2232-4b5e-9697-68cc7e382cc3.dcm

[149/3468] b51c4cd4-6b0b-4abc-9a05-499e51d9f1c7.dcm

[150/3468] d9d5b55b-5dce-4da0-a7ed-edeca7f563c9.dcm

[151/3468] 4691a0c1-b74c-43e0-9220-238ee8803f47.dcm

[152/3468] 2134d10d-ca81-4d06-bf7d-f3c71679fcac.dcm

[153/3468] 385cab7f-79aa-409c-acf9-6a248469cdf0.dcm

[154/3468] 1b2af2e9-0248-4176-a43d-904e72d984d3.dcm

[155/3468] 5bb79e2f-442b-42d7-9a2a-2653d372bdd6.dcm

[156/3468] 15866e0f-d392-492e-bb95-1550c1b1b1eb.dcm

[157/3468] 326e0947-e465-4169-a561-b602336b9f3d.dcm

[158/3468] 606ace88-558c-4a4d-8fff-4586327e9457.dcm

[159/3468] d52f9145-0073-40e3-8ac6-088ff5739080.dcm

[160/3468] de14c497-dff4-4c6c-ab59-95eba4e96f8e.dcm

[161/3468] 888df9d8-88cb-4d0c-9b87-15dd59260f69.dcm

[162/3468] c15ecdbe-01b1-427f-ae20-7e5c95a38a84.dcm

[163/3468] d178842b-9005-45d0-b48d-9e016a64c2a4.dcm

[164/3468] 64e5ed48-322b-4e7c-8d20-99bf79c9c05f.dcm

[165/3468] c89a51f3-1fb6-4dd5-be73-993ce500eeda.dcm

[166/3468] d47bd5c7-540c-4bac-a465-0f0f8b3867b9.dcm

[167/3468] aecd1c0f-9de8-46bd-9ecf-90ae60dd4342.dcm

[168/3468] 0f6d77e4-7a59-43fd-90f1-ebed7bd89622.dcm

[169/3468] c18b5c5e-dabd-4f54-bba6-bcb3872b2adb.dcm

[170/3468] 8ef8ee12-8f13-4f78-bcd4-b5c2448fb9df.dcm

[171/3468] 1890a0ce-0d29-491a-ba79-194c61c30257.dcm

[172/3468] 86744e6f-0884-40c0-99b7-412cbde928bb.dcm

[173/3468] db60cb8f-5340-44bb-a294-2fc28e7975a0.dcm

[174/3468] 303f50e5-4fb5-48ac-94c9-b99392229a10.dcm

[175/3468] 7bcf43b4-df5a-4b67-8754-1314546e13ce.dcm

[176/3468] d385738b-5c8a-4d51-983d-89ae1c5ec127.dcm

[177/3468] 6ad2d664-fe43-473c-803f-826113c6672e.dcm

[178/3468] b7129297-ee82-4d92-9ee8-a1715e351906.dcm

[179/3468] 347f71f3-4b3a-4616-a030-8d459f6a3eda.dcm

[180/3468] 79e72000-3dc6-467c-938e-536c2fc80c28.dcm

[181/3468] bae7d82d-8ece-44d8-816d-db4248e086bf.dcm

[182/3468] a250825a-474d-431b-a124-44fd12dd0f4b.dcm

[183/3468] 56dbf335-3473-4757-a7d2-e4d45b9fac26.dcm

[184/3468] 9dd89393-ee45-4bba-8fb3-55f3062d191f.dcm

[185/3468] 32243c76-8120-43ef-9772-7f355ad2c81a.dcm

[186/3468] a713270d-fe33-41e2-b643-25e942324160.dcm

[187/3468] 581e25e0-6040-42ab-93fd-34fca9151746.dcm

[188/3468] 8d8a3db4-1c4f-4569-becf-e155e462373c.dcm

[189/3468] 63fa3a14-5095-4040-a841-ca27d6d1bce0.dcm

[190/3468] 2adc0ce9-4753-40b0-a616-908f1e55db59.dcm

[191/3468] bc165b24-c564-47ea-b354-8d294f73989d.dcm

[192/3468] 1fd102bc-ed1c-410c-9167-698f97989be9.dcm

[193/3468] 5eb7417b-e01f-47db-b629-37e0aa6eac5f.dcm

[194/3468] 56dc1516-b8c1-48f6-b54e-e1be359f5e4a.dcm

[195/3468] c02208e2-c15c-4900-8cff-6e05b5c48419.dcm

[196/3468] 5f2eacdc-3de3-48aa-8958-df9c31c4f847.dcm

[197/3468] bebee480-ac46-4e28-88e8-ece44f78d4c0.dcm

[198/3468] 12d80282-49c6-42e1-aed2-319ee09f0e7e.dcm

[199/3468] 87c72b26-615c-4ef5-89d0-efbda9040a77.dcm

[200/3468] 7914857f-1e59-481c-ad24-62e54c5130fd.dcm

[201/3468] e76bd7fb-51e6-4e15-a5e7-0cf6285814fa.dcm

[202/3468] 21884785-d8ae-49e7-9e57-0fec548babcc.dcm

[203/3468] dd445cb2-153b-4762-ac12-f854146bd187.dcm

[204/3468] 4858792e-07aa-4729-9d1e-a73e9795afc5.dcm

[205/3468] 8e8f5648-7b0a-410b-a958-25f0193e0e8c.dcm

[206/3468] eb8984c6-f4ec-49b3-aa47-420f4a08cd4c.dcm

[207/3468] 4d6a92ef-6a08-4f65-8586-d18fcd08148b.dcm

[208/3468] 10e88f41-7458-4180-bcd9-45ac7d451a76.dcm

[209/3468] af7caf91-450e-4833-8e76-cc0e0fb9e6f3.dcm

[210/3468] 01545a64-725d-4510-b368-83133602e896.dcm

[211/3468] 3452ed1a-06ab-4402-8010-759114c9e51a.dcm

[212/3468] 31829df5-bffc-4049-a7ed-7f75ded78eb8.dcm

[213/3468] 8f9cd455-f9ca-4876-8bf9-55c4ddf1a6d3.dcm

[214/3468] ec27d49a-7d83-48a2-b09b-2b299b2632fa.dcm

[215/3468] 673dad38-be63-4d19-a3af-2a3b663431f0.dcm

[216/3468] 184edc19-c624-4321-896b-fd14f837e5b9.dcm

[217/3468] 7c9488dd-ee45-412f-bd75-a7c2aecd72c8.dcm

[218/3468] 97afeb4e-b112-4943-b97c-a731e4b806d5.dcm

[219/3468] 4ddd96ed-0f55-4a96-9ddb-780a7c446789.dcm

[220/3468] 38f30b92-bb09-4215-81bd-404dbe74bc35.dcm

[221/3468] 59da46cb-46fb-440f-8a24-195f16aaa67b.dcm

[222/3468] 0765af16-7418-424a-8528-a4a5787f58e7.dcm

[223/3468] 77cc3373-6a6c-4652-910b-6f022db95fa1.dcm

[224/3468] 0d0779c0-2b0c-4edc-a150-4602d0d55b4d.dcm

[225/3468] e1463838-6151-4886-bc4f-65dada2feaf1.dcm

[226/3468] 8765dc25-d566-4b41-a111-5377205413b5.dcm

[227/3468] 864c1281-8e64-4924-ada0-a866ff7016c8.dcm

[228/3468] e98f8b64-a325-4e4e-900a-84725219de6d.dcm

[229/3468] 5a2e470a-471f-44f6-be93-f06801497061.dcm

[230/3468] e16016ea-3948-4ae7-9463-7f0c4db2f060.dcm

[231/3468] a6a4b85c-bcde-4397-a1e0-996050f0e64e.dcm

[232/3468] 619b1657-bf45-49d7-9fdf-1fe5913df269.dcm

[233/3468] 51df0671-b703-403d-b1cb-c539c5513f82.dcm

[234/3468] 824a7e3d-73de-4287-9c60-f4d25e83e920.dcm

[235/3468] e5fe08e0-c47f-4d2d-912f-8c1a618d1e8f.dcm

[236/3468] 6403c3cb-1b5e-4a7a-8f10-af4a291bf6ca.dcm

[237/3468] ee779a10-9183-428e-b9d1-1fa08e3f09df.dcm

[238/3468] 6e5d2d24-0003-4515-a9a3-92bcf17469b5.dcm

[239/3468] c7a760a8-9fb3-45c5-8595-4c147c8117a3.dcm

[240/3468] 2bec8e5a-dc7a-4930-8e64-01453304c075.dcm

[241/3468] b08baa88-1f9c-49a2-ab8c-962ff3c5a021.dcm

[242/3468] 626966e6-e0d0-44f7-8013-264ebe96aa87.dcm

[243/3468] 5fa33efa-9764-4f2e-9e30-055677aa1ced.dcm

[244/3468] bd2ad64c-92c0-4f0c-930d-9a1a54f955e8.dcm

[245/3468] d17d4343-b5f7-49cf-8dcd-08e5b75a0f37.dcm

[246/3468] 0d97ddf7-9c66-4f95-9723-17d837988847.dcm

[247/3468] dd7e299d-b8e2-4ed6-b74a-4800d03980aa.dcm

[248/3468] bbc5650b-3c1a-4eaa-947a-3ff6a44165b0.dcm

[249/3468] 769e25fc-f77c-48ee-abed-bf8e497788e9.dcm

[250/3468] c48d9bb0-df93-4ac1-9d69-aaea5072c7ec.dcm

[251/3468] ee675629-2366-4600-b6b5-614e45d98ed5.dcm

[252/3468] 88439254-be35-40e4-940e-661ee799a81a.dcm

[253/3468] f0150523-d29d-48c8-af06-c8f42b389af0.dcm

[254/3468] 278ca33e-9bd0-44a7-ab2f-625f4859b00f.dcm

[255/3468] 7f230009-04c7-4858-b3fe-000128891246.dcm

[256/3468] f7ec48c3-b6f9-41f2-9cdf-366202500c37.dcm

[257/3468] 67433208-d530-46fb-8616-81cefbf2839d.dcm

[258/3468] 0f39038f-d7dd-4eb0-a6d4-9d9f5a9305d6.dcm

[259/3468] d765e758-d013-4174-b5d5-caa33ffc8de3.dcm

[260/3468] 20ae4eef-7bca-45c6-abc1-720a04ee0ebd.dcm

[261/3468] 5882ab4c-109d-414d-9d5f-b08b26b7d551.dcm

[262/3468] 4fcbc39e-06d5-4ee8-a778-a22b340758ca.dcm

[263/3468] 78703232-6662-4765-bdbc-a72a627bf46f.dcm

[264/3468] b204816a-50eb-4c99-816f-7a199f7847f0.dcm

[265/3468] 80e1d24c-5b5c-4d53-967d-b551292bee83.dcm

[266/3468] 1fe69c90-c11a-47df-bda2-4b26359bcdeb.dcm

[267/3468] 01312e0d-4ddd-4042-b541-c38ad79bcaa2.dcm

[268/3468] d75ece91-2670-49a7-a5e0-aa26a95a17de.dcm

[269/3468] 2a738437-5c73-40b2-975a-1221a4174f45.dcm

[270/3468] 9f0e0bc5-f913-4c65-86b5-f8e04f53fb12.dcm

[271/3468] ced22455-3780-4199-8b6d-be403ce71805.dcm

[272/3468] 72b8c19a-d460-48a2-8342-527f35e2b8b9.dcm

[273/3468] 258c5bda-956e-43d3-be43-bfce15351364.dcm

[274/3468] b3ede530-9ffb-4708-9299-3455ce44390d.dcm

[275/3468] 5d81a045-1128-435e-8d36-fd077e94033f.dcm

[276/3468] 35896633-6771-4b42-b900-2ad1b7f7e1eb.dcm

[277/3468] 8ba0740b-9101-4c2c-bff8-da486a3b044e.dcm

[278/3468] ee08932f-018f-4cba-ba69-6e75f4c543b5.dcm

[279/3468] 64792e5b-edd9-4f26-a1a3-23fa31334ac6.dcm

[280/3468] 510287a7-77e2-4802-9082-7823249440e8.dcm

[281/3468] d6d2b984-2cc7-4d51-9668-887f1eec6b09.dcm

[282/3468] 451b1a09-0893-49d1-b980-ef2b351fbb92.dcm

[283/3468] 7847a0c1-b37c-463f-b43d-eac919ebc68f.dcm

[284/3468] 3caf9c40-ed4d-4015-8d71-a40eaf2ee5d9.dcm

[285/3468] f16d6214-60dd-4544-88d5-f13034f4bfeb.dcm

[286/3468] 234292c5-5304-4cf8-8915-4268784d019e.dcm

[287/3468] 329e3829-7c88-4fc1-9d5c-5326ef38d011.dcm

[288/3468] edf6a536-971c-4649-b071-4489338b8711.dcm

[289/3468] f2efc6bf-8ee8-48b0-b258-cc74bca00c9b.dcm

[290/3468] 9cd73590-2612-4670-851d-314a1ed6b5cb.dcm

[291/3468] 298c4f9a-419a-465a-95a9-cf801bbb05c2.dcm

[292/3468] 83668049-7899-4b1b-a764-53e315bee858.dcm

[293/3468] 6793f29d-ff08-499a-84c8-f9d19007ca67.dcm

[294/3468] f78b2e67-12d4-407e-b613-eb00753088bc.dcm

[295/3468] 292d2631-effa-4b17-ab7f-95e357a0d1b3.dcm

[296/3468] 3a211bda-c919-4c59-982a-f8029a8ad8fd.dcm

[297/3468] b8941333-66ea-4a4b-90af-c713ac2f1319.dcm

[298/3468] 62f42b6f-1363-4349-b48f-f950e9d37dd4.dcm

[299/3468] 996c6fc3-0f5c-48d7-9cc3-6fa04c6f4fe9.dcm

[300/3468] dd83aca2-8c1d-4593-ae47-b6c6a5d66ea4.dcm

[301/3468] 930b95ac-9e5a-4dce-b905-913fc0e35318.dcm

[302/3468] 65516d18-413b-4c30-96a6-86d213e0ea35.dcm

[303/3468] 73f29055-cf22-4488-adae-6628615fd132.dcm

[304/3468] 55bc9d18-a591-4d76-9a73-358980874e81.dcm

[305/3468] c121a3db-3dcf-43c9-b938-650b40ce7bb6.dcm

[306/3468] c93c02d3-8c26-4c61-b240-dfcff5e317ed.dcm

[307/3468] 31af5818-decc-462e-b1d3-d371eb03223a.dcm

[308/3468] b37ba794-f182-4109-9752-99bdaa26e148.dcm

[309/3468] b22af290-1647-4613-9f23-0d61d614987f.dcm

[310/3468] 1ea43a02-b7bf-4bc8-a597-0bc6605f2908.dcm

[311/3468] 64f49afc-a7cc-48b1-b839-0f59c3376eb9.dcm

[312/3468] 64de50a6-03ed-4e69-bad2-cddc3584e680.dcm

[313/3468] d609c533-538b-4cd4-b96d-0e498c302b43.dcm

[314/3468] 4572d001-2e50-4639-b479-3eeaf4421841.dcm

[315/3468] b0bf1601-c563-4219-a769-2e4387f52df1.dcm

[316/3468] aae8f762-c92f-4d18-95a2-189bd385347b.dcm

[317/3468] 8f60cb73-3fae-47bc-82a3-45836c5bcaac.dcm

[318/3468] a6d8393f-11e9-4c97-8fd6-d0027281f7e0.dcm

[319/3468] 1f06598a-f23f-406e-baaa-45b3b2ebe2c2.dcm

[320/3468] 77f9877f-3a3b-46c8-abcf-b44bde8650f8.dcm

[321/3468] 2a830e97-1209-4d3b-9410-d9b6de3e2bea.dcm

[322/3468] 494ecd3a-f015-4f9e-9b4a-3d8c04607d3b.dcm

[323/3468] 276c575c-5d44-42fa-98fa-2c8ac87d7531.dcm

[324/3468] e43e1490-0682-4542-997d-4fb3552504a1.dcm

[325/3468] 1d6b8499-3740-4091-90d0-3ba730d3db7f.dcm

[326/3468] 7a5fac4d-1317-4df3-9c49-4a2863917795.dcm

[327/3468] 3f4fd79b-8622-439e-8ad2-a621273825a7.dcm

[328/3468] 0daade2e-c2e3-47b2-bd53-bed7143b1196.dcm

[329/3468] 277bdcff-25d6-4432-9d90-6c383568ecc4.dcm

[330/3468] 06de612d-4259-42f2-891e-cf9da2a32623.dcm

[331/3468] 226888e2-3bf8-4409-934d-2e11c0e14d46.dcm

[332/3468] b03646f3-977b-4eaf-a869-f4d481315832.dcm

[333/3468] fe965e84-fcd3-4eb2-bf31-169664420955.dcm

[334/3468] 95c067e9-f48c-424d-8523-472d2bf64dda.dcm

[335/3468] 6ea13686-ae11-40c5-ad12-fb065f07f19b.dcm

[336/3468] e2329098-06eb-4871-9527-ff32b16b6cad.dcm

[337/3468] e4c7a2c4-31d2-409a-b596-6e59e8af3b2f.dcm

[338/3468] d5c6f483-cbdb-4d1b-a741-80d249c8c01b.dcm

[339/3468] 6c5c5bad-a272-4174-9bfb-9145265acd36.dcm

[340/3468] e229f305-0ec1-479c-b58f-d2a75483ae55.dcm

[341/3468] ed5ab3a0-4e8d-4346-bf03-7f1d86068705.dcm

[342/3468] 7339cc61-abf0-4ed8-b79d-5f177332e8b8.dcm

[343/3468] 09fec51f-bbff-42ac-ba77-1463255ec5ba.dcm

[344/3468] 769e8023-53c4-4552-bc8c-353228235577.dcm

[345/3468] 9fda7c1d-8d83-491b-a8d3-249815dfcb86.dcm

[346/3468] b43f4b4d-39e3-4488-8680-4d9be5353859.dcm

[347/3468] 257f05b6-05b0-4e1e-9526-77784126cea3.dcm

[348/3468] cba39c47-bab2-4436-9865-093df89f0143.dcm

[349/3468] 25d07f40-a220-4077-bf44-4d5b71be2cfd.dcm

[350/3468] a10076f4-1e1b-4cb0-b735-d50865d5d4bb.dcm

[351/3468] 431389b4-6e15-4223-8d74-ca4024a3cde4.dcm

[352/3468] ead7764f-12c0-449b-adc6-4c2735c54869.dcm

[353/3468] 906ca8a1-b20c-436a-9738-5e5d04a9b2e1.dcm

[354/3468] 5d7da55c-4ee4-4b0d-a292-16ac5cde02bd.dcm

[355/3468] 08bcb294-d5c9-4bb1-b8ac-e28cacbaf158.dcm

[356/3468] 8bd82051-0a61-43d6-9e8a-232eb8405120.dcm

[357/3468] 9ec4f1a0-bb51-447d-942e-b4d6b0cb9065.dcm

[358/3468] cdd4d44c-a921-4caf-b0e9-b93b4a4502ef.dcm

[359/3468] dc5da079-66ae-42fc-9ac6-e5a3d1ad8904.dcm

[360/3468] c9ad3421-9418-497b-9bf0-eccb5d5cadb8.dcm

[361/3468] 539ec7f3-580e-421a-a8e9-1fffb668a7ca.dcm

[362/3468] 24834987-45d5-4795-a46e-1f3111fa7021.dcm

[363/3468] c970e3c0-e198-40ec-9cae-d3ade7bc0032.dcm

[364/3468] 329e7d92-3380-4759-9b22-67ecbeeadee5.dcm

[365/3468] 334d87c6-5772-418d-a511-573e8ea24f19.dcm

[366/3468] d6a675f2-c269-4a95-88ef-d099905d1dea.dcm

[367/3468] cacd5eaa-bbad-47fd-9626-88b5f07867a9.dcm

[368/3468] 93b95ba4-51a4-43d4-920d-e7c789820272.dcm

[369/3468] b5b40e40-eb68-4044-a0f5-70e30336f054.dcm

[370/3468] 357c2de7-cee8-446f-9b83-ccbc4471c4b3.dcm

[371/3468] b07d656b-b67d-4f87-855c-eac6b58229fc.dcm

[372/3468] a12889d4-bc3c-444d-a74e-01cdfa25d531.dcm

[373/3468] 4510724c-8d27-4d1a-9c5c-f891acee4a68.dcm

[374/3468] 6bbb2a5a-f6aa-4d3a-af62-80825a371171.dcm

[375/3468] 176144c8-9a33-472c-9a91-6476121b4e0f.dcm

[376/3468] 93bca189-cb39-4fb3-a10a-58a480bff234.dcm

[377/3468] f5c18027-73b0-4108-a8a3-d2072b77d258.dcm

[378/3468] 3aa96a83-310e-4c66-96fe-5881f4748d9f.dcm

[379/3468] 6da4183d-8008-4670-a25e-7952f11e29d9.dcm

[380/3468] 9c94dde0-d038-441b-91ca-4b08f8087439.dcm

[381/3468] e4a9e0c9-89d3-44ce-970a-797dd32859cf.dcm

[382/3468] 8130212e-cc26-46c2-ac6b-f1e3e15ff634.dcm

[383/3468] f323650b-5727-48f2-acbd-231eec4902ff.dcm

[384/3468] bb6f5765-3dcb-4542-8cbe-c4c03be1e3e3.dcm

[385/3468] fe1cfde0-8886-4edb-8229-9baaf949115e.dcm

[386/3468] fea06f4f-60fa-4cea-9fe0-8ca1d6214417.dcm

[387/3468] e5da8fad-c992-427c-9e3b-8d3b763ae741.dcm

[388/3468] 53006e78-6a5b-4fc9-9fdd-2f512d238d13.dcm

[389/3468] d0d2891b-a6ef-415a-ac41-1d4522e2df10.dcm

[390/3468] 427eb33d-557e-4caf-90da-751c39b3921c.dcm

[391/3468] 1991bbd9-3354-4ded-87a0-95cdb95bc6e5.dcm

[392/3468] 51e53227-6353-4551-ba9a-8c58a1dbf95a.dcm

[393/3468] 4d4196e8-4a12-41a8-b8ad-72163c2437df.dcm

[394/3468] 3a595bc1-1f6c-4be4-887e-10648110f042.dcm

[395/3468] c1109a20-72ca-4211-a838-9d4758e6d85a.dcm

[396/3468] 4625a1c6-fbdf-404d-9774-f94d43bcaed1.dcm

[397/3468] 1ae4f7be-e2bc-4baf-adf6-27e49102cda1.dcm

[398/3468] 7e273289-4931-489b-aaf3-b19231325a38.dcm

[399/3468] 29ee1795-d780-44e3-8983-d099c8dcd0e8.dcm

[400/3468] aff8a845-a69b-4c16-b68c-6dce61f8f84e.dcm

[401/3468] 69329aea-c374-4406-afcc-3e5e0ba5823e.dcm

[402/3468] 1a3b1c79-a64a-44fb-84b0-79e0eb11c9e9.dcm

[403/3468] bec3d3e6-fd89-4eb1-b65b-62e0a63bfad0.dcm

[404/3468] 74803a4c-ecdc-4ad2-96d0-d43dd813509c.dcm

[405/3468] e641d8a3-f147-438e-ab24-9f2382ce6184.dcm

[406/3468] 4ef8e17d-be75-4520-9291-904e5b674b83.dcm

[407/3468] 01c2cec7-641b-4433-a40b-02a7c75195c2.dcm


In [11]:
# ============================================================
# DATAFRAME
# ============================================================

df = pd.DataFrame(results)

print()

print(df.head())

print()

print("Rows :", len(df))

print("Columns :", len(df.columns))

                                                File      Filename  \
0  C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...  Q3EDC380.dcm
1  C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...  Q3EDCA02.dcm
2  C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...  Q3EDCBG4.dcm
3  C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...  Q3EDCH86.dcm
4  C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...  Q3EDCK08.dcm

   ReaderCount  PyDICOM_OK  SimpleITK_OK  MONAI_OK   Py_Time  SimpleITK_Time  \
0            3        True          True      True  1.278399        2.012048
1            3        True          True      True  1.245472        2.038860
2            3        True          True      True  2.416232        3.716097
3            3        True          True      True  0.030084        0.252722
4            3        True          True      True  0.043748        0.348895

   MONAI_Time  Py_Throughput  ...  LossyImageCompression  \
0    1.437810   2.126926e+08  ...                     01
1    1.424576   2.183155e+08  ...                     01
2    2.578268   2.054175e+08  ...                     01
3    0.367378   7.173267e+07  ...                     01
4    0.340372   4.932772e+07  ...                     01

   LossyImageCompressionMethod   Photometric Color TransferSyntax  \
0                               YBR_FULL_422  True           JPEG
1                               YBR_FULL_422  True           JPEG
2                               YBR_FULL_422  True           JPEG
3                               YBR_FULL_422  True           JPEG
4                               YBR_FULL_422  True           JPEG

  ValidationStatus               FailureReason Frames_PyDICOM  \
0          WARNING      PyDICOM vs MONAI Shape            126
1          WARNING      PyDICOM vs MONAI Shape            126
2          WARNING      PyDICOM vs MONAI Shape            230
3          WARNING  PyDICOM vs SimpleITK Shape              1
4          WARNING  PyDICOM vs SimpleITK Shape              1

   Frames_SimpleITK  Frames_MONAI
0               126           708
1               126           708
2               230           708
3                 1             1
4                 1             1

[5 rows x 54 columns]

Rows : 3468
Columns : 54

In [12]:
# ============================================================
# SAVE CSV
# ============================================================

df.to_csv(
    CSV_PATH,
    index=False
)

print()

print("CSV Saved")

print(CSV_PATH)

CSV Saved
benchmark_results\benchmark.csv

# IMPROVED COMPARISON

In [13]:
# ============================================================
# IMPROVED COMPARISON
# ============================================================

improved_results=[]

print("="*80)
print("Detailed Comparison")
print("="*80)

for i,row in enumerate(results):

    dcm=Path(row["File"])

    print(f"{i+1}/{len(results)}")

    py=read_with_pydicom(dcm)

    sitk_result=read_with_simpleitk(dcm)

    monai=read_with_monai(dcm)

    py_pixels=canonicalize_array(py["pixels"])

    sitk_pixels=canonicalize_array(sitk_result["pixels"])

    monai_pixels=canonicalize_array(monai["pixels"])

    py_vs_sitk=pixel_difference_report(
        py_pixels,
        sitk_pixels
    )

    py_vs_monai=pixel_difference_report(
        py_pixels,
        monai_pixels
    )

    sitk_vs_monai=pixel_difference_report(
        sitk_pixels,
        monai_pixels
    )

    improved_results.append({

        "File":str(dcm),

        "Py==SimpleITK":
            py_vs_sitk.get("equal"),

        "Py==MONAI":
            py_vs_monai.get("equal"),

        "SimpleITK==MONAI":
            sitk_vs_monai.get("equal"),

        "Py_MONAI_RMSE":
            py_vs_monai.get("rmse"),

        "Py_SITK_RMSE":
            py_vs_sitk.get("rmse"),

        "SITK_MONAI_RMSE":
            sitk_vs_monai.get("rmse"),

        "Py_MONAI_MaxError":
            py_vs_monai.get("max_error"),

        "Py_SITK_MaxError":
            py_vs_sitk.get("max_error"),

        "SITK_MONAI_MaxError":
            sitk_vs_monai.get("max_error"),

        "Py_MONAI_DifferentPixels":
            py_vs_monai.get("different_pixels"),

        "Py_SITK_DifferentPixels":
            py_vs_sitk.get("different_pixels"),

        "SITK_MONAI_DifferentPixels":
            sitk_vs_monai.get("different_pixels"),

    })

print()

print("Done.")

================================================================================
Detailed Comparison
================================================================================
1/3468
2/3468
3/3468
4/3468
5/3468
6/3468
7/3468
8/3468
9/3468
10/3468
11/3468
12/3468
13/3468
14/3468
15/3468
16/3468
17/3468
18/3468
19/3468
20/3468
21/3468
22/3468
23/3468
24/3468
25/3468
26/3468
27/3468
28/3468
29/3468

The decoded RLE segment contains non-conformant padding - 276025 vs. 276024 bytes expected

30/3468
31/3468
32/3468
33/3468
34/3468
35/3468
36/3468
37/3468
38/3468
39/3468
40/3468
41/3468
42/3468
43/3468
44/3468
45/3468
46/3468
47/3468
48/3468
49/3468
50/3468
51/3468
52/3468
53/3468
54/3468
55/3468
56/3468
57/3468
58/3468
59/3468
60/3468
61/3468
62/3468
63/3468
64/3468
65/3468
66/3468
67/3468
68/3468
69/3468
70/3468
71/3468
72/3468
73/3468
74/3468
75/3468
76/3468
77/3468
78/3468
79/3468
80/3468
81/3468
82/3468
83/3468
84/3468
85/3468
86/3468
87/3468
88/3468
89/3468
90/3468
91/3468
92/3468
93/3468
94/3468
95/3468
96/3468
97/3468
98/3468
99/3468
100/3468
101/3468
102/3468
103/3468
104/3468
105/3468
106/3468
107/3468
108/3468
109/3468
110/3468
111/3468
112/3468
113/3468
114/3468
115/3468
116/3468
117/3468
118/3468
119/3468
120/3468
121/3468
122/3468
123/3468
124/3468
125/3468
126/3468
127/3468
128/3468
129/3468
130/3468
131/3468
132/3468
133/3468
134/3468
135/3468
136/3468
137/3468
138/3468
139/3468
140/3468
141/3468
142/3468
143/3468
144/3468
145/3468
146/3468
147/3468
148/3468
149/3468
150/3468
151/3468
152/3468
153/3468
154/3468
155/3468
156/3468
157/3468
158/3468
159/3468
160/3468
161/3468
162/3468
163/3468
164/3468
165/3468
166/3468
167/3468
168/3468
169/3468
170/3468
171/3468
172/3468
173/3468
174/3468
175/3468
176/3468
177/3468
178/3468
179/3468
180/3468
181/3468
182/3468
183/3468
184/3468
185/3468
186/3468
187/3468
188/3468
189/3468
190/3468
191/3468
192/3468
193/3468
194/3468
195/3468
196/3468
197/3468
198/3468
199/3468
200/3468
201/3468
202/3468
203/3468
204/3468
205/3468
206/3468
207/3468
208/3468
209/3468
210/3468
211/3468
212/3468
213/3468
214/3468
215/3468
216/3468
217/3468
218/3468
219/3468
220/3468
221/3468
222/3468
223/3468
224/3468
225/3468
226/3468
227/3468
228/3468
229/3468
230/3468
231/3468
232/3468
233/3468
234/3468
235/3468
236/3468
237/3468
238/3468
239/3468
240/3468
241/3468
242/3468
243/3468
244/3468
245/3468
246/3468
247/3468
248/3468
249/3468
250/3468
251/3468
252/3468
253/3468
254/3468
255/3468
256/3468
257/3468
258/3468
259/3468
260/3468
261/3468
262/3468
263/3468
264/3468
265/3468
266/3468
267/3468
268/3468
269/3468
270/3468
271/3468
272/3468
273/3468
274/3468
275/3468
276/3468
277/3468
278/3468
279/3468
280/3468
281/3468
282/3468
283/3468
284/3468
285/3468
286/3468
287/3468
288/3468
289/3468
290/3468
291/3468
292/3468
293/3468
294/3468
295/3468
296/3468
297/3468
298/3468
299/3468
300/3468
301/3468
302/3468
303/3468
304/3468
305/3468
306/3468
307/3468
308/3468
309/3468
310/3468
311/3468
312/3468
313/3468
314/3468
315/3468
316/3468
317/3468
318/3468
319/3468
320/3468
321/3468
322/3468
323/3468
324/3468
325/3468
326/3468
327/3468
328/3468
329/3468
330/3468
331/3468
332/3468
333/3468
334/3468
335/3468
336/3468
337/3468
338/3468
339/3468
340/3468
341/3468
342/3468
343/3468
344/3468
345/3468
346/3468
347/3468
348/3468
349/3468
350/3468
351/3468
352/3468
353/3468
354/3468
355/3468
356/3468
357/3468
358/3468
359/3468
360/3468
361/3468
362/3468
363/3468
364/3468
365/3468
366/3468
367/3468
368/3468
369/3468
370/3468
371/3468
372/3468
373/3468
374/3468
375/3468
376/3468
377/3468
378/3468
379/3468
380/3468
381/3468
382/3468
383/3468
384/3468
385/3468
386/3468
387/3468
388/3468
389/3468
390/3468
391/3468
392/3468
393/3468
394/3468
395/3468
396/3468
397/3468
398/3468
399/3468
400/3468
401/3468
402/3468
403/3468
404/3468
405/3468
406/3468
407/3468
408/3468
409/3468
410/3468
411/3468
412/3468
413/3468
414/3468
415/3468
416/3468
417/3468
418/3468
419/3468
420/3468
421/3468
422/3468
423/3468
424/3468
425/3468
426/3468
427/3468
428/3468
429/3468
430/3468
431/3468
432/3468
433/3468
434/3468
435/3468
436/3468
437/3468
438/3468
439/3468
440/3468
441/3468
442/3468
443/3468
444/3468
445/3468
446/3468
447/3468
448/3468
449/3468
450/3468
451/3468
452/3468
453/3468
454/3468
455/3468
456/3468
457/3468
458/3468
459/3468
460/3468
461/3468
462/3468
463/3468
464/3468
465/3468
466/3468
467/3468
468/3468
469/3468
470/3468
471/3468
472/3468
473/3468
474/3468
475/3468
476/3468
477/3468
478/3468
479/3468
480/3468
481/3468
482/3468
483/3468
484/3468
485/3468
486/3468
487/3468
488/3468
489/3468
490/3468
491/3468
492/3468
493/3468
494/3468
495/3468
496/3468
497/3468
498/3468
499/3468
500/3468
501/3468
502/3468
503/3468
504/3468
505/3468
506/3468
507/3468
508/3468
509/3468
510/3468
511/3468
512/3468
513/3468
514/3468
515/3468
516/3468
517/3468
518/3468
519/3468
520/3468
521/3468
522/3468
523/3468
524/3468
525/3468
526/3468
527/3468
528/3468
529/3468
530/3468
531/3468
532/3468
533/3468
534/3468
535/3468
536/3468
537/3468
538/3468
539/3468
540/3468
541/3468
542/3468
543/3468
544/3468
545/3468
546/3468
547/3468
548/3468
549/3468
550/3468
551/3468
552/3468
553/3468
554/3468
555/3468
556/3468
557/3468
558/3468
559/3468
560/3468
561/3468
562/3468
563/3468
564/3468
565/3468
566/3468
567/3468
568/3468
569/3468
570/3468
571/3468
572/3468
573/3468
574/3468
575/3468
576/3468
577/3468
578/3468
579/3468
580/3468
581/3468
582/3468
583/3468
584/3468
585/3468
586/3468
587/3468
588/3468
589/3468
590/3468
591/3468
592/3468
593/3468
594/3468
595/3468
596/3468
597/3468
598/3468
599/3468
600/3468
601/3468
602/3468
603/3468
604/3468
605/3468
606/3468
607/3468
608/3468
609/3468
610/3468
611/3468
612/3468
613/3468
614/3468
615/3468
616/3468
617/3468
618/3468
619/3468
620/3468
621/3468
622/3468
623/3468
624/3468
625/3468
626/3468
627/3468
628/3468
629/3468
630/3468
631/3468
632/3468
633/3468
634/3468
635/3468
636/3468
637/3468
638/3468
639/3468
640/3468
641/3468
642/3468
643/3468
644/3468
645/3468
646/3468
647/3468
648/3468
649/3468
650/3468
651/3468
652/3468
653/3468
654/3468
655/3468
656/3468
657/3468
658/3468
659/3468
660/3468
661/3468
662/3468
663/3468
664/3468
665/3468
666/3468
667/3468
668/3468
669/3468
670/3468
671/3468
672/3468
673/3468
674/3468
675/3468
676/3468
677/3468
678/3468
679/3468
680/3468
681/3468
682/3468
683/3468
684/3468
685/3468
686/3468
687/3468
688/3468
689/3468
690/3468
691/3468
692/3468
693/3468
694/3468
695/3468
696/3468
697/3468
698/3468
699/3468
700/3468
701/3468
702/3468
703/3468
704/3468
705/3468
706/3468
707/3468
708/3468
709/3468
710/3468
711/3468
712/3468
713/3468
714/3468
715/3468
716/3468
717/3468
718/3468
719/3468
720/3468
721/3468
722/3468
723/3468
724/3468
725/3468
726/3468
727/3468
728/3468
729/3468
730/3468
731/3468
732/3468
733/3468
734/3468
735/3468
736/3468
737/3468
738/3468
739/3468
740/3468
741/3468
742/3468
743/3468
744/3468
745/3468
746/3468
747/3468
748/3468
749/3468
750/3468
751/3468
752/3468
753/3468
754/3468
755/3468
756/3468
757/3468
758/3468
759/3468
760/3468
761/3468
762/3468
763/3468
764/3468
765/3468
766/3468
767/3468
768/3468
769/3468
770/3468
771/3468
772/3468
773/3468
774/3468
775/3468
776/3468
777/3468
778/3468
779/3468
780/3468
781/3468
782/3468
783/3468
784/3468
785/3468
786/3468
787/3468
788/3468
789/3468
790/3468
791/3468
792/3468
793/3468
794/3468
795/3468
796/3468
797/3468
798/3468
799/3468
800/3468
801/3468
802/3468
803/3468
804/3468
805/3468
806/3468
807/3468
808/3468
809/3468
810/3468
811/3468
812/3468
813/3468
814/3468
815/3468
816/3468
817/3468
818/3468
819/3468
820/3468
821/3468
822/3468
823/3468
824/3468
825/3468
826/3468
827/3468
828/3468
829/3468
830/3468
831/3468
832/3468
833/3468
834/3468
835/3468
836/3468
837/3468
838/3468
839/3468
840/3468
841/3468
842/3468
843/3468
844/3468
845/3468
846/3468
847/3468
848/3468
849/3468
850/3468
851/3468
852/3468
853/3468
854/3468
855/3468
856/3468
857/3468
858/3468
859/3468
860/3468
861/3468
862/3468
863/3468
864/3468
865/3468
866/3468
867/3468
868/3468
869/3468
870/3468
871/3468
872/3468
873/3468
874/3468
875/3468
876/3468
877/3468
878/3468
879/3468
880/3468
881/3468
882/3468
883/3468
884/3468
885/3468
886/3468
887/3468
888/3468
889/3468
890/3468
891/3468
892/3468
893/3468
894/3468
895/3468
896/3468
897/3468
898/3468
899/3468
900/3468
901/3468
902/3468
903/3468
904/3468
905/3468
906/3468
907/3468
908/3468
909/3468
910/3468
911/3468
912/3468
913/3468
914/3468
915/3468
916/3468
917/3468
918/3468
919/3468
920/3468
921/3468
922/3468
923/3468
924/3468
925/3468
926/3468
927/3468
928/3468
929/3468
930/3468
931/3468
932/3468
933/3468
934/3468
935/3468
936/3468
937/3468
938/3468
939/3468
940/3468
941/3468
942/3468
943/3468
944/3468
945/3468
946/3468
947/3468
948/3468
949/3468
950/3468
951/3468
952/3468
953/3468
954/3468
955/3468
956/3468
957/3468
958/3468
959/3468
960/3468
961/3468
962/3468
963/3468
964/3468
965/3468
966/3468
967/3468
968/3468
969/3468
970/3468
971/3468
972/3468
973/3468
974/3468
975/3468
976/3468
977/3468
978/3468
979/3468
980/3468
981/3468
982/3468
983/3468
984/3468
985/3468
986/3468
987/3468
988/3468
989/3468
990/3468
991/3468
992/3468
993/3468
994/3468
995/3468
996/3468
997/3468
998/3468
999/3468
1000/3468
1001/3468
1002/3468
1003/3468
1004/3468
1005/3468
1006/3468
1007/3468
1008/3468
1009/3468
1010/3468
1011/3468
1012/3468
1013/3468
1014/3468
1015/3468
1016/3468
1017/3468
1018/3468
1019/3468
1020/3468
1021/3468
1022/3468
1023/3468
1024/3468
1025/3468
1026/3468
1027/3468
1028/3468
1029/3468
1030/3468
1031/3468
1032/3468
1033/3468
1034/3468
1035/3468
1036/3468
1037/3468
1038/3468
1039/3468
1040/3468
1041/3468
1042/3468
1043/3468
1044/3468
1045/3468
1046/3468
1047/3468
1048/3468
1049/3468
1050/3468
1051/3468
1052/3468
1053/3468
1054/3468
1055/3468
1056/3468
1057/3468
1058/3468
1059/3468
1060/3468
1061/3468
1062/3468
1063/3468
1064/3468
1065/3468
1066/3468
1067/3468
1068/3468
1069/3468
1070/3468
1071/3468
1072/3468
1073/3468
1074/3468
1075/3468
1076/3468
1077/3468
1078/3468
1079/3468
1080/3468
1081/3468
1082/3468
1083/3468
1084/3468
1085/3468
1086/3468
1087/3468
1088/3468
1089/3468
1090/3468
1091/3468
1092/3468
1093/3468
1094/3468
1095/3468
1096/3468
1097/3468
1098/3468
1099/3468
1100/3468
1101/3468
1102/3468
1103/3468
1104/3468
1105/3468
1106/3468
1107/3468
1108/3468
1109/3468
1110/3468
1111/3468
1112/3468
1113/3468
1114/3468
1115/3468
1116/3468
1117/3468
1118/3468
1119/3468
1120/3468
1121/3468
1122/3468
1123/3468
1124/3468
1125/3468
1126/3468
1127/3468
1128/3468
1129/3468
1130/3468
1131/3468
1132/3468
1133/3468
1134/3468
1135/3468
1136/3468
1137/3468
1138/3468
1139/3468
1140/3468
1141/3468
1142/3468
1143/3468
1144/3468
1145/3468
1146/3468
1147/3468
1148/3468
1149/3468
1150/3468
1151/3468
1152/3468
1153/3468
1154/3468
1155/3468
1156/3468
1157/3468
1158/3468
1159/3468
1160/3468
1161/3468
1162/3468
1163/3468
1164/3468
1165/3468
1166/3468
1167/3468
1168/3468
1169/3468
1170/3468
1171/3468
1172/3468
1173/3468
1174/3468
1175/3468
1176/3468
1177/3468
1178/3468
1179/3468
1180/3468
1181/3468
1182/3468
1183/3468
1184/3468
1185/3468
1186/3468
1187/3468
1188/3468
1189/3468
1190/3468
1191/3468
1192/3468
1193/3468
1194/3468
1195/3468
1196/3468
1197/3468
1198/3468
1199/3468
1200/3468
1201/3468
1202/3468
1203/3468
1204/3468
1205/3468
1206/3468
1207/3468
1208/3468
1209/3468
1210/3468
1211/3468
1212/3468
1213/3468
1214/3468
1215/3468
1216/3468
1217/3468
1218/3468
1219/3468
1220/3468
1221/3468
1222/3468
1223/3468
1224/3468
1225/3468
1226/3468
1227/3468
1228/3468
1229/3468
1230/3468
1231/3468
1232/3468
1233/3468
1234/3468
1235/3468
1236/3468
1237/3468
1238/3468
1239/3468
1240/3468
1241/3468
1242/3468
1243/3468
1244/3468
1245/3468
1246/3468
1247/3468
1248/3468
1249/3468
1250/3468
1251/3468
1252/3468
1253/3468
1254/3468
1255/3468
1256/3468
1257/3468
1258/3468
1259/3468
1260/3468
1261/3468
1262/3468
1263/3468
1264/3468
1265/3468
1266/3468
1267/3468
1268/3468
1269/3468
1270/3468
1271/3468
1272/3468
1273/3468
1274/3468
1275/3468
1276/3468
1277/3468
1278/3468
1279/3468
1280/3468
1281/3468
1282/3468
1283/3468
1284/3468
1285/3468
1286/3468
1287/3468
1288/3468
1289/3468
1290/3468
1291/3468
1292/3468
1293/3468
1294/3468
1295/3468
1296/3468
1297/3468
1298/3468
1299/3468
1300/3468
1301/3468
1302/3468
1303/3468
1304/3468
1305/3468
1306/3468
1307/3468
1308/3468
1309/3468
1310/3468
1311/3468
1312/3468
1313/3468
1314/3468
1315/3468
1316/3468
1317/3468
1318/3468
1319/3468
1320/3468
1321/3468
1322/3468
1323/3468
1324/3468
1325/3468
1326/3468
1327/3468
1328/3468
1329/3468
1330/3468
1331/3468
1332/3468
1333/3468
1334/3468
1335/3468
1336/3468
1337/3468
1338/3468
1339/3468
1340/3468
1341/3468
1342/3468
1343/3468
1344/3468
1345/3468
1346/3468
1347/3468
1348/3468
1349/3468
1350/3468
1351/3468
1352/3468
1353/3468
1354/3468
1355/3468
1356/3468
1357/3468
1358/3468
1359/3468
1360/3468
1361/3468
1362/3468
1363/3468
1364/3468
1365/3468
1366/3468
1367/3468
1368/3468
1369/3468
1370/3468
1371/3468
1372/3468
1373/3468
1374/3468
1375/3468
1376/3468
1377/3468
1378/3468
1379/3468
1380/3468
1381/3468
1382/3468
1383/3468
1384/3468
1385/3468
1386/3468
1387/3468
1388/3468
1389/3468
1390/3468
1391/3468
1392/3468
1393/3468
1394/3468
1395/3468
1396/3468
1397/3468
1398/3468
1399/3468
1400/3468
1401/3468
1402/3468
1403/3468
1404/3468
1405/3468
1406/3468
1407/3468
1408/3468
1409/3468
1410/3468
1411/3468
1412/3468
1413/3468
1414/3468
1415/3468
1416/3468
1417/3468
1418/3468
1419/3468
1420/3468
1421/3468
1422/3468
1423/3468
1424/3468
1425/3468
1426/3468
1427/3468
1428/3468
1429/3468
1430/3468
1431/3468
1432/3468
1433/3468
1434/3468
1435/3468
1436/3468
1437/3468
1438/3468
1439/3468
1440/3468
1441/3468
1442/3468
1443/3468
1444/3468
1445/3468
1446/3468
1447/3468
1448/3468
1449/3468
1450/3468
1451/3468
1452/3468
1453/3468
1454/3468
1455/3468
1456/3468
1457/3468
1458/3468
1459/3468
1460/3468
1461/3468
1462/3468
1463/3468
1464/3468
1465/3468
1466/3468
1467/3468
1468/3468
1469/3468
1470/3468
1471/3468
1472/3468
1473/3468
1474/3468
1475/3468
1476/3468
1477/3468
1478/3468
1479/3468
1480/3468
1481/3468
1482/3468
1483/3468
1484/3468
1485/3468
1486/3468
1487/3468
1488/3468
1489/3468
1490/3468
1491/3468
1492/3468
1493/3468
1494/3468
1495/3468
1496/3468
1497/3468
1498/3468
1499/3468
1500/3468
1501/3468
1502/3468
1503/3468
1504/3468
1505/3468
1506/3468
1507/3468
1508/3468
1509/3468
1510/3468
1511/3468
1512/3468
1513/3468
1514/3468
1515/3468
1516/3468
1517/3468
1518/3468
1519/3468
1520/3468
1521/3468
1522/3468
1523/3468
1524/3468
1525/3468
1526/3468
1527/3468
1528/3468
1529/3468
1530/3468
1531/3468
1532/3468
1533/3468
1534/3468
1535/3468
1536/3468
1537/3468
1538/3468
1539/3468
1540/3468
1541/3468
1542/3468
1543/3468
1544/3468
1545/3468
1546/3468
1547/3468
1548/3468
1549/3468
1550/3468
1551/3468
1552/3468
1553/3468
1554/3468
1555/3468
1556/3468
1557/3468
1558/3468
1559/3468
1560/3468
1561/3468
1562/3468
1563/3468
1564/3468
1565/3468
1566/3468
1567/3468
1568/3468
1569/3468
1570/3468
1571/3468
1572/3468
1573/3468
1574/3468
1575/3468
1576/3468
1577/3468
1578/3468
1579/3468
1580/3468
1581/3468
1582/3468
1583/3468
1584/3468
1585/3468
1586/3468
1587/3468
1588/3468
1589/3468
1590/3468
1591/3468
1592/3468
1593/3468
1594/3468
1595/3468
1596/3468
1597/3468
1598/3468
1599/3468
1600/3468
1601/3468
1602/3468
1603/3468
1604/3468
1605/3468
1606/3468
1607/3468
1608/3468
1609/3468
1610/3468
1611/3468
1612/3468
1613/3468
1614/3468
1615/3468
1616/3468
1617/3468
1618/3468
1619/3468
1620/3468
1621/3468
1622/3468
1623/3468
1624/3468
1625/3468
1626/3468
1627/3468
1628/3468
1629/3468
1630/3468
1631/3468
1632/3468
1633/3468
1634/3468
1635/3468
1636/3468
1637/3468
1638/3468
1639/3468
1640/3468
1641/3468
1642/3468
1643/3468
1644/3468
1645/3468
1646/3468
1647/3468
1648/3468
1649/3468
1650/3468
1651/3468
1652/3468
1653/3468
1654/3468
1655/3468
1656/3468
1657/3468
1658/3468
1659/3468
1660/3468
1661/3468
1662/3468
1663/3468
1664/3468
1665/3468
1666/3468
1667/3468
1668/3468
1669/3468
1670/3468
1671/3468
1672/3468
1673/3468
1674/3468
1675/3468
1676/3468
1677/3468
1678/3468
1679/3468
1680/3468
1681/3468
1682/3468
1683/3468
1684/3468
1685/3468
1686/3468
1687/3468
1688/3468
1689/3468
1690/3468
1691/3468
1692/3468
1693/3468
1694/3468
1695/3468
1696/3468
1697/3468
1698/3468
1699/3468
1700/3468
1701/3468
1702/3468
1703/3468
1704/3468
1705/3468
1706/3468
1707/3468
1708/3468
1709/3468
1710/3468
1711/3468
1712/3468
1713/3468
1714/3468
1715/3468
1716/3468
1717/3468
1718/3468
1719/3468
1720/3468
1721/3468
1722/3468
1723/3468
1724/3468
1725/3468
1726/3468
1727/3468
1728/3468
1729/3468
1730/3468
1731/3468
1732/3468
1733/3468
1734/3468
1735/3468
1736/3468
1737/3468
1738/3468
1739/3468
1740/3468
1741/3468
1742/3468
1743/3468
1744/3468
1745/3468
1746/3468
1747/3468
1748/3468
1749/3468
1750/3468
1751/3468
1752/3468
1753/3468
1754/3468
1755/3468
1756/3468
1757/3468
1758/3468
1759/3468
1760/3468
1761/3468
1762/3468
1763/3468
1764/3468
1765/3468
1766/3468
1767/3468
1768/3468
1769/3468
1770/3468
1771/3468
1772/3468
1773/3468
1774/3468
1775/3468
1776/3468
1777/3468
1778/3468
1779/3468
1780/3468
1781/3468
1782/3468
1783/3468
1784/3468
1785/3468
1786/3468
1787/3468
1788/3468
1789/3468
1790/3468
1791/3468
1792/3468
1793/3468
1794/3468
1795/3468
1796/3468
1797/3468
1798/3468
1799/3468
1800/3468
1801/3468
1802/3468
1803/3468
1804/3468
1805/3468
1806/3468
1807/3468
1808/3468
1809/3468
1810/3468
1811/3468
1812/3468
1813/3468
1814/3468
1815/3468
1816/3468
1817/3468
1818/3468
1819/3468
1820/3468
1821/3468
1822/3468
1823/3468
1824/3468
1825/3468
1826/3468
1827/3468
1828/3468
1829/3468
1830/3468
1831/3468
1832/3468
1833/3468
1834/3468
1835/3468
1836/3468
1837/3468
1838/3468
1839/3468
1840/3468
1841/3468
1842/3468
1843/3468
1844/3468
1845/3468
1846/3468
1847/3468
1848/3468
1849/3468
1850/3468
1851/3468
1852/3468
1853/3468
1854/3468
1855/3468
1856/3468
1857/3468
1858/3468
1859/3468
1860/3468
1861/3468
1862/3468
1863/3468
1864/3468
1865/3468
1866/3468
1867/3468
1868/3468
1869/3468
1870/3468
1871/3468
1872/3468
1873/3468
1874/3468
1875/3468
1876/3468
1877/3468
1878/3468
1879/3468
1880/3468
1881/3468
1882/3468
1883/3468
1884/3468
1885/3468
1886/3468
1887/3468
1888/3468
1889/3468
1890/3468
1891/3468
1892/3468
1893/3468
1894/3468
1895/3468
1896/3468
1897/3468
1898/3468
1899/3468
1900/3468
1901/3468
1902/3468
1903/3468
1904/3468
1905/3468
1906/3468
1907/3468
1908/3468
1909/3468
1910/3468
1911/3468
1912/3468
1913/3468
1914/3468
1915/3468
1916/3468
1917/3468
1918/3468
1919/3468
1920/3468
1921/3468
1922/3468
1923/3468
1924/3468
1925/3468
1926/3468
1927/3468
1928/3468
1929/3468
1930/3468
1931/3468
1932/3468
1933/3468
1934/3468
1935/3468
1936/3468
1937/3468
1938/3468
1939/3468
1940/3468
1941/3468
1942/3468
1943/3468
1944/3468
1945/3468
1946/3468
1947/3468
1948/3468
1949/3468
1950/3468
1951/3468
1952/3468
1953/3468
1954/3468
1955/3468
1956/3468
1957/3468
1958/3468
1959/3468
1960/3468
1961/3468
1962/3468
1963/3468
1964/3468
1965/3468
1966/3468
1967/3468
1968/3468
1969/3468
1970/3468
1971/3468
1972/3468
1973/3468
1974/3468
1975/3468
1976/3468
1977/3468
1978/3468
1979/3468
1980/3468
1981/3468
1982/3468
1983/3468
1984/3468
1985/3468
1986/3468
1987/3468
1988/3468
1989/3468
1990/3468
1991/3468
1992/3468
1993/3468
1994/3468
1995/3468
1996/3468
1997/3468
1998/3468
1999/3468
2000/3468
2001/3468
2002/3468
2003/3468
2004/3468
2005/3468
2006/3468
2007/3468
2008/3468
2009/3468
2010/3468
2011/3468
2012/3468
2013/3468
2014/3468
2015/3468
2016/3468
2017/3468
2018/3468
2019/3468
2020/3468
2021/3468
2022/3468
2023/3468
2024/3468
2025/3468
2026/3468
2027/3468
2028/3468
2029/3468
2030/3468
2031/3468
2032/3468
2033/3468
2034/3468
2035/3468
2036/3468
2037/3468
2038/3468
2039/3468
2040/3468
2041/3468
2042/3468
2043/3468
2044/3468
2045/3468
2046/3468
2047/3468
2048/3468
2049/3468
2050/3468
2051/3468
2052/3468
2053/3468
2054/3468
2055/3468
2056/3468
2057/3468
2058/3468
2059/3468
2060/3468
2061/3468
2062/3468
2063/3468
2064/3468
2065/3468
2066/3468
2067/3468
2068/3468
2069/3468
2070/3468
2071/3468
2072/3468
2073/3468
2074/3468
2075/3468
2076/3468
2077/3468
2078/3468
2079/3468
2080/3468
2081/3468
2082/3468
2083/3468
2084/3468
2085/3468
2086/3468
2087/3468
2088/3468
2089/3468
2090/3468
2091/3468
2092/3468
2093/3468
2094/3468
2095/3468
2096/3468
2097/3468
2098/3468
2099/3468
2100/3468
2101/3468
2102/3468
2103/3468
2104/3468
2105/3468
2106/3468
2107/3468
2108/3468
2109/3468
2110/3468
2111/3468
2112/3468
2113/3468
2114/3468
2115/3468
2116/3468
2117/3468
2118/3468
2119/3468
2120/3468
2121/3468
2122/3468
2123/3468
2124/3468
2125/3468
2126/3468
2127/3468
2128/3468
2129/3468
2130/3468
2131/3468
2132/3468
2133/3468

In [14]:
comparison_df=pd.DataFrame(improved_results)

comparison_csv=OUTPUT_DIR/"pixel_comparison.csv"

comparison_df.to_csv(
    comparison_csv,
    index=False
)

comparison_df.head()

,File,Py==SimpleITK,Py==MONAI,SimpleITK==MONAI,Py_MONAI_RMSE,Py_SITK_RMSE,SITK_MONAI_RMSE,Py_MONAI_MaxError,Py_SITK_MaxError,SITK_MONAI_MaxError,Py_MONAI_DifferentPixels,Py_SITK_DifferentPixels,SITK_MONAI_DifferentPixels
0,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...,False,None,None,NaN,91.792781,None,NaN,238.0,None,NaN,207166236.0,None
1,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...,False,None,None,NaN,91.792778,None,NaN,238.0,None,NaN,207165985.0,None
2,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...,False,None,None,NaN,86.959729,None,NaN,238.0,None,NaN,384563199.0,None
3,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...,None,None,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN,None
4,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\AI...,None,None,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN,None

In [15]:
print("="*80)
print("SUMMARY")
print("="*80)

pairs=[

    "Py==SimpleITK",

    "Py==MONAI",

    "SimpleITK==MONAI"

]

for p in pairs:

    total=comparison_df[p].count()

    equal=comparison_df[p].sum()

    print()

    print(p)

    print("Equal :",equal)

    print("Different :",total-equal)

    print("Agreement : %.2f%%"%(100*equal/total))

================================================================================
SUMMARY
================================================================================

Py==SimpleITK
Equal : 2083
Different : 9
Agreement : 99.57%

Py==MONAI
Equal : 0
Different : 1296
Agreement : 0.00%

SimpleITK==MONAI
Equal : 0
Different : 0
Agreement : nan%

invalid value encountered in scalar divide

In [16]:
print("="*80)
print("Largest RMSE")
print("="*80)

comparison_df.sort_values(

    "Py_MONAI_RMSE",

    ascending=False

).head(20)

================================================================================
Largest RMSE
================================================================================

,File,Py==SimpleITK,Py==MONAI,SimpleITK==MONAI,Py_MONAI_RMSE,Py_SITK_RMSE,SITK_MONAI_RMSE,Py_MONAI_MaxError,Py_SITK_MaxError,SITK_MONAI_MaxError,Py_MONAI_DifferentPixels,Py_SITK_DifferentPixels,SITK_MONAI_DifferentPixels
3026,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,109.955579,NaN,None,575.0,NaN,None,76192.0,NaN,None
2282,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,109.955579,NaN,None,575.0,NaN,None,76192.0,NaN,None
2525,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,97.008382,NaN,None,737.0,NaN,None,76374.0,NaN,None
3269,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,97.008382,NaN,None,737.0,NaN,None,76374.0,NaN,None
2294,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,96.162756,NaN,None,442.0,NaN,None,75798.0,NaN,None
3038,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,96.162756,NaN,None,442.0,NaN,None,75798.0,NaN,None
2524,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,85.564555,NaN,None,504.0,NaN,None,73616.0,NaN,None
3268,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,85.564555,NaN,None,504.0,NaN,None,73616.0,NaN,None
3267,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,85.476373,NaN,None,518.0,NaN,None,73428.0,NaN,None
2523,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,85.476373,NaN,None,518.0,NaN,None,73428.0,NaN,None
3015,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,83.903436,NaN,None,508.0,NaN,None,73840.0,NaN,None
2271,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,83.903436,NaN,None,508.0,NaN,None,73840.0,NaN,None
3257,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,83.389818,NaN,None,689.0,NaN,None,76496.0,NaN,None
2513,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,83.389818,NaN,None,689.0,NaN,None,76496.0,NaN,None
2522,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,81.326210,NaN,None,548.0,NaN,None,72936.0,NaN,None
3266,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,81.326210,NaN,None,548.0,NaN,None,72936.0,NaN,None
3118,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,79.128139,NaN,None,822.0,NaN,None,78164.0,NaN,None
2374,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,79.128139,NaN,None,822.0,NaN,None,78164.0,NaN,None
2272,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,78.816362,NaN,None,518.0,NaN,None,73952.0,NaN,None
3016,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,78.816362,NaN,None,518.0,NaN,None,73952.0,NaN,None

In [17]:
comparison_df.sort_values(

    "Py_MONAI_DifferentPixels",

    ascending=False

).head(20)

,File,Py==SimpleITK,Py==MONAI,SimpleITK==MONAI,Py_MONAI_RMSE,Py_SITK_RMSE,SITK_MONAI_RMSE,Py_MONAI_MaxError,Py_SITK_MaxError,SITK_MONAI_MaxError,Py_MONAI_DifferentPixels,Py_SITK_DifferentPixels,SITK_MONAI_DifferentPixels
3316,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,65.127237,NaN,None,490.0,NaN,None,115388.0,NaN,None
3324,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,62.201784,NaN,None,407.0,NaN,None,115242.0,NaN,None
3315,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,66.566390,NaN,None,495.0,NaN,None,115204.0,NaN,None
2776,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,50.618486,NaN,None,458.0,NaN,None,115198.0,NaN,None
2210,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,50.618486,NaN,None,458.0,NaN,None,115198.0,NaN,None
3318,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,63.966947,NaN,None,445.0,NaN,None,115170.0,NaN,None
3320,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,63.562045,NaN,None,417.0,NaN,None,115148.0,NaN,None
3319,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,63.703809,NaN,None,416.0,NaN,None,115130.0,NaN,None
3462,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,58.563663,NaN,None,667.0,NaN,None,115128.0,NaN,None
2220,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,50.053505,NaN,None,487.0,NaN,None,115076.0,NaN,None
2786,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,50.053505,NaN,None,487.0,NaN,None,115076.0,NaN,None
3458,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,57.761980,NaN,None,670.0,NaN,None,115064.0,NaN,None
3317,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,63.962878,NaN,None,449.0,NaN,None,115040.0,NaN,None
3313,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,66.167311,NaN,None,513.0,NaN,None,115024.0,NaN,None
3457,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,57.479612,NaN,None,588.0,NaN,None,115012.0,NaN,None
3314,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,66.602764,NaN,None,458.0,NaN,None,115012.0,NaN,None
3293,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,58.167829,NaN,None,524.0,NaN,None,115010.0,NaN,None
3310,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,67.173582,NaN,None,494.0,NaN,None,115008.0,NaN,None
3311,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,66.893595,NaN,None,495.0,NaN,None,115002.0,NaN,None
3307,C:\Users\Gajendra\Desktop\D3_MONAI\Datasets\UT...,None,False,None,63.757568,NaN,None,510.0,NaN,None,115000.0,NaN,None

In [18]:
print("="*80)
print("Average Read Time")
print("="*80)

print(

    df[

        [

            "Py_Time",

            "SimpleITK_Time",

            "MONAI_Time"

        ]

    ].mean()

)

================================================================================
Average Read Time
================================================================================
Py_Time           0.038962
SimpleITK_Time    0.095818
MONAI_Time        0.120159
dtype: float64

In [19]:
# row.update(dicom_info)

# row.update(photo_info)

# row["TransferSyntax"] = syntax

# row["ValidationStatus"] = failure["Status"]

# row["FailureReason"] = failure["Reason"]

# row["Frames_PyDICOM"] = frame_count(py["pixels"])

# row["Frames_SimpleITK"] = frame_count(sitk_result["pixels"])

# row["Frames_MONAI"] = frame_count(monai["pixels"])

In [20]:
print("="*80)
print("Transfer Syntax Summary")
print("="*80)

print(

    df.groupby("TransferSyntax")

      .size()

      .sort_values(ascending=False)

)

================================================================================
Transfer Syntax Summary
================================================================================
TransferSyntax
Explicit VR Little    3442
RLE                     14
JPEG                    12
dtype: int64

In [21]:
print("="*80)
print("Photometric Interpretation")
print("="*80)

print(

    df.groupby("PhotometricInterpretation")

      .size()

      .sort_values(ascending=False)

)

================================================================================
Photometric Interpretation
================================================================================
PhotometricInterpretation
MONOCHROME2      3425
RGB                17
PALETTE COLOR      14
YBR_FULL_422       11
YBR_FULL            1
dtype: int64

In [22]:
print("="*80)
print("Failure Summary")
print("="*80)

print(

    df.groupby("FailureReason")

      .size()

      .sort_values(ascending=False)

)

================================================================================
Failure Summary
================================================================================
FailureReason
PyDICOM vs MONAI Shape        2092
PyDICOM vs SimpleITK Shape    1376
dtype: int64

In [23]:
print("="*80)
print("Average Read Time")
print("="*80)

print(

    df[

        [

            "Py_Time",

            "SimpleITK_Time",

            "MONAI_Time"

        ]

    ].describe()

)

================================================================================
Average Read Time
================================================================================
           Py_Time  SimpleITK_Time   MONAI_Time
count  3468.000000     3468.000000  3468.000000
mean      0.038962        0.095818     0.120159
std       0.077998        0.141117     0.181800
min       0.001518        0.004220     0.002586
25%       0.002260        0.004999     0.002943
50%       0.032432        0.089417     0.095441
75%       0.057104        0.157111     0.170346
max       2.416232        3.716097     4.079869

In [24]:
# ============================================================
# MISMATCH OUTPUT
# ============================================================

MISMATCH_DIR = OUTPUT_DIR / "Mismatches"
MISMATCH_DIR.mkdir(exist_ok=True)

In [25]:
def get_display_frame(arr):
    """
    Convert any DICOM pixel array to a displayable image.

    Supported inputs:
        (H,W)
        (H,W,3)
        (F,H,W)
        (F,H,W,3)
        (C,H,W)
        (F,C,H,W)

    Returns
        (H,W) or (H,W,3)
    """

    if arr is None:
        return None

    arr = canonicalize_array(arr)

    if arr.ndim == 2:
        return arr

    if arr.ndim == 3:

        # RGB
        if arr.shape[-1] in (3,4):
            return arr

        # Multi-frame grayscale
        return arr[0]

    if arr.ndim == 4:

        # First RGB frame
        return arr[0]

    return arr

In [26]:
import matplotlib.pyplot as plt

def save_comparison_images(
    filename,
    py_img,
    sitk_img,
    monai_img,
):

    # py_img = canonicalize_array(py_img)
    # sitk_img = canonicalize_array(sitk_img)
    # monai_img = canonicalize_array(monai_img)

    py_img = get_display_frame(py_img)
    sitk_img = get_display_frame(sitk_img)
    monai_img = get_display_frame(monai_img)

    if py_img is None or sitk_img is None or monai_img is None:
        return

    # first frame only

    if py_img.ndim == 3 and py_img.shape[-1] not in (3,4):
        py_img = py_img[0]

    if sitk_img.ndim == 3 and sitk_img.shape[-1] not in (3,4):
        sitk_img = sitk_img[0]

    if monai_img.ndim == 3 and monai_img.shape[-1] not in (3,4):
        monai_img = monai_img[0]

    fig,ax = plt.subplots(1,3,figsize=(15,5))

    ax[0].imshow(py_img,cmap="gray")
    ax[0].set_title("PyDICOM")

    ax[1].imshow(sitk_img,cmap="gray")
    ax[1].set_title("SimpleITK")

    ax[2].imshow(monai_img,cmap="gray")
    ax[2].set_title("MONAI")

    for a in ax:
        a.axis("off")

    plt.tight_layout()

    plt.savefig(
        MISMATCH_DIR / (filename + ".png"),
        dpi=200
    )

    plt.close()

In [27]:
def save_difference_image(
    filename,
    img1,
    img2,
    title,
):

    img1 = canonicalize_array(img1)
    img2 = canonicalize_array(img2)

    if img1.shape != img2.shape:
        return

    if img1.ndim == 3 and img1.shape[-1] not in (3,4):
        img1 = img1[0]

    if img2.ndim == 3 and img2.shape[-1] not in (3,4):
        img2 = img2[0]

    diff = np.abs(
        img1.astype(np.float32)
        -
        img2.astype(np.float32)
    )

    plt.figure(figsize=(6,6))

    plt.imshow(diff,cmap="hot")

    plt.colorbar()

    plt.title(title)

    plt.axis("off")

    plt.savefig(
        MISMATCH_DIR /
        (filename + "_" + title + ".png"),
        dpi=200
    )

    plt.close()

In [28]:
if not np.array_equal(
    canonicalize_array(py["pixels"]),
    canonicalize_array(monai["pixels"])
):

    save_comparison_images(
        dcm_file.stem,
        py["pixels"],
        sitk_result["pixels"],
        monai["pixels"],
    )

    save_difference_image(
        dcm_file.stem,
        py["pixels"],
        monai["pixels"],
        "Py_vs_MONAI"
    )

In [29]:
def compare_metadata_values(py_ds, monai_meta):

    comparison = {}

    important = [

        "Rows",

        "Columns",

        "BitsAllocated",

        "BitsStored",

        "SamplesPerPixel",

        "PhotometricInterpretation",

        "PixelRepresentation",

        "NumberOfFrames",

    ]

    for tag in important:

        py_value = str(py_ds.get(tag,""))

        monai_value = str(
            monai_meta.get(tag,"")
        )

        comparison[tag] = py_value == monai_value

    return comparison

In [30]:
# row["Py_Throughput"] = throughput(
#     py["pixels"],
#     py["time"]
# )

# row["SimpleITK_Throughput"] = throughput(
#     sitk_result["pixels"],
#     sitk_result["time"]
# )

# row["MONAI_Throughput"] = throughput(
#     monai["pixels"],
#     monai["time"]
# )

In [31]:
def agreement_score(row):

    score = 0

    score += int(row["PyDICOM_OK"])
    score += int(row["SimpleITK_OK"])
    score += int(row["MONAI_OK"])

    score += int(row["Py_vs_MONAI_Equal"])
    score += int(row["Py_vs_SimpleITK_Equal"])
    score += int(row["SimpleITK_vs_MONAI_Equal"])

    return score

In [32]:
df["AgreementScore"] = df.apply(
    agreement_score,
    axis=1
)

In [33]:
print("=" * 80)
print("FINAL VALIDATION REPORT")
print("=" * 80)

print(f"Total DICOMs          : {len(df)}")
print(f"PyDICOM Success       : {df['PyDICOM_OK'].sum()}")
print(f"SimpleITK Success     : {df['SimpleITK_OK'].sum()}")
print(f"MONAI Success         : {df['MONAI_OK'].sum()}")

print()

print("Exact Pixel Agreement")

print(f"PyDICOM vs SimpleITK : {df['Py_vs_SimpleITK_Equal'].sum()}")
print(f"PyDICOM vs MONAI     : {df['Py_vs_MONAI_Equal'].sum()}")
print(f"SimpleITK vs MONAI   : {df['SimpleITK_vs_MONAI_Equal'].sum()}")

print()

print("Average Read Time (seconds)")

print(df[
    [
        "Py_Time",
        "SimpleITK_Time",
        "MONAI_Time"
    ]
].mean())

print()

print("Average Throughput (pixels/sec)")

print(df[
    [
        "Py_Throughput",
        "SimpleITK_Throughput",
        "MONAI_Throughput"
    ]
].mean())

================================================================================
FINAL VALIDATION REPORT
================================================================================
Total DICOMs          : 3468
PyDICOM Success       : 3468
SimpleITK Success     : 3468
MONAI Success         : 3468

Exact Pixel Agreement
PyDICOM vs SimpleITK : 2083
PyDICOM vs MONAI     : 0
SimpleITK vs MONAI   : 0

Average Read Time (seconds)
Py_Time           0.038962
SimpleITK_Time    0.095818
MONAI_Time        0.120159
dtype: float64

Average Throughput (pixels/sec)
Py_Throughput           5.245102e+08
SimpleITK_Throughput    2.004841e+08
MONAI_Throughput        1.827836e+08
dtype: float64

# VISUALIZATION (Plotting)

In [38]:
# ============================================================
# VISUALIZATION SETUP
# ============================================================

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

PLOT_DIR = OUTPUT_DIR / "Plots"
PLOT_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams["figure.dpi"] = 150
plt.rcParams["savefig.dpi"] = 300
plt.rcParams["font.size"] = 11

In [39]:
def plot_reader_success(df):

    success = [
        df["PyDICOM_OK"].sum(),
        df["SimpleITK_OK"].sum(),
        df["MONAI_OK"].sum(),
    ]

    labels = [
        "PyDICOM",
        "SimpleITK",
        "MONAI",
    ]

    plt.figure(figsize=(6,4))

    plt.bar(labels, success)

    plt.ylabel("Successful Reads")

    plt.title("Reader Success")

    for i,v in enumerate(success):
        plt.text(i,v,f"{v}",ha="center",va="bottom")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"reader_success.png")

    plt.close()

In [40]:
def plot_runtime(df):

    plt.figure(figsize=(7,5))

    plt.boxplot([
        df["Py_Time"],
        df["SimpleITK_Time"],
        df["MONAI_Time"],
    ])

    plt.xticks(
        [1,2,3],
        [
            "PyDICOM",
            "SimpleITK",
            "MONAI",
        ]
    )

    plt.ylabel("Read Time (seconds)")

    plt.title("Reader Runtime Distribution")

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"runtime_boxplot.png")

    plt.close()

In [41]:
def plot_transfer_syntax(df):

    counts = (
        df["TransferSyntax"]
        .value_counts()
        .sort_values()
    )

    plt.figure(figsize=(9,5))

    counts.plot(kind="barh")

    plt.xlabel("Number of Files")

    plt.title("Transfer Syntax Distribution")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"transfer_syntax.png")

    plt.close()

In [42]:
def plot_photometric(df):

    counts = (
        df["PhotometricInterpretation"]
        .value_counts()
        .sort_values()
    )

    plt.figure(figsize=(8,5))

    counts.plot(kind="barh")

    plt.xlabel("Number of Files")

    plt.title("Photometric Interpretation")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"photometric.png")

    plt.close()

In [43]:
def plot_manufacturer(df):

    counts = (
        df["Manufacturer"]
        .fillna("Unknown")
        .value_counts()
    )

    plt.figure(figsize=(9,5))

    counts.plot(kind="bar")

    plt.ylabel("Files")

    plt.title("Manufacturer Distribution")

    plt.xticks(rotation=45,ha="right")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"manufacturer.png")

    plt.close()

In [44]:
def plot_agreement_heatmap(df):

    matrix = np.array([
        [
            100,
            df["Py_vs_SimpleITK_Equal"].mean()*100,
            df["Py_vs_MONAI_Equal"].mean()*100,
        ],
        [
            df["Py_vs_SimpleITK_Equal"].mean()*100,
            100,
            df["SimpleITK_vs_MONAI_Equal"].mean()*100,
        ],
        [
            df["Py_vs_MONAI_Equal"].mean()*100,
            df["SimpleITK_vs_MONAI_Equal"].mean()*100,
            100,
        ]
    ])

    labels=[
        "PyDICOM",
        "SimpleITK",
        "MONAI",
    ]

    plt.figure(figsize=(6,5))

    plt.imshow(matrix)

    plt.xticks(range(3),labels)

    plt.yticks(range(3),labels)

    for i in range(3):
        for j in range(3):

            plt.text(
                j,
                i,
                f"{matrix[i,j]:.1f}%",
                ha="center",
                va="center",
                fontsize=11
            )

    plt.colorbar(label="Agreement (%)")

    plt.title("Reader Agreement")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"agreement_heatmap.png")

    plt.close()

In [45]:
def plot_rmse(df):

    plt.figure(figsize=(7,5))

    plt.hist(
        df["Py_vs_MONAI_RMSE"].dropna(),
        bins=40
    )

    plt.xlabel("RMSE")

    plt.ylabel("Number of Files")

    plt.title("PyDICOM vs MONAI RMSE")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"rmse_histogram.png")

    plt.close()

In [46]:
def plot_max_error(df):

    plt.figure(figsize=(7,5))

    plt.hist(
        df["Py_vs_MONAI_MaxError"].dropna(),
        bins=40
    )

    plt.xlabel("Maximum Pixel Error")

    plt.ylabel("Files")

    plt.title("Maximum Pixel Difference")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"max_error_histogram.png")

    plt.close()

In [47]:
def plot_throughput(df):

    mean_values=[

        df["Py_Throughput"].mean(),

        df["SimpleITK_Throughput"].mean(),

        df["MONAI_Throughput"].mean(),

    ]

    labels=[

        "PyDICOM",

        "SimpleITK",

        "MONAI",

    ]

    plt.figure(figsize=(6,4))

    plt.bar(labels,mean_values)

    plt.ylabel("Pixels / second")

    plt.title("Average Decoder Throughput")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"throughput.png")

    plt.close()

In [48]:
def plot_failure_reasons(df):

    counts=(
        df["FailureReason"]
        .fillna("PASS")
        .value_counts()
    )

    plt.figure(figsize=(7,7))

    plt.pie(
        counts.values,
        labels=counts.index,
        autopct="%1.1f%%"
    )

    plt.title("Failure Classification")

    plt.savefig(PLOT_DIR/"failure_reasons.png")

    plt.close()

In [49]:
def plot_failure_reasons(df):

    counts=(
        df["FailureReason"]
        .fillna("PASS")
        .value_counts()
    )

    plt.figure(figsize=(7,7))

    plt.pie(
        counts.values,
        labels=counts.index,
        autopct="%1.1f%%"
    )

    plt.title("Failure Classification")

    plt.savefig(PLOT_DIR/"failure_reasons.png")

    plt.close()

In [50]:
def plot_runtime_vs_size(df):

    pixels=[]

    for s in df["Py_Shape"]:

        try:

            shape=eval(s)

            pixels.append(np.prod(shape))

        except:

            pixels.append(np.nan)

    plt.figure(figsize=(7,5))

    plt.scatter(
        pixels,
        df["Py_Time"],
        s=12
    )

    plt.xlabel("Number of Pixels")

    plt.ylabel("Read Time (s)")

    plt.title("Runtime vs Image Size")

    plt.tight_layout()

    plt.savefig(PLOT_DIR/"runtime_vs_pixels.png")

    plt.close()

In [51]:
plot_reader_success(df)

plot_runtime(df)

plot_transfer_syntax(df)

plot_photometric(df)

plot_manufacturer(df)

plot_agreement_heatmap(df)

plot_rmse(df)

plot_max_error(df)

plot_throughput(df)

plot_failure_reasons(df)

plot_runtime_vs_size(df)

print(f"Plots saved to:\n{PLOT_DIR}")

Plots saved to:
benchmark_results\Plots